services:
  - type: web
    name: acl-rehab-app
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FILE_RETENTION_HOURS
        value: 1
      - key: ANALYSIS_RETENTION_DAYS
        value: 1
      - key: MAX_FILE_SIZE
        value: 52428800
    healthCheckPath: /health
    autoDeploy: true
    region: oregon