exports.seed = async function(knex) {
  // Delete all existing entries
  await knex('exercises').del();
  
  // Get category IDs
  const categories = await knex('exercise_categories').select('id', 'name', 'phase');
  
  const getCategory = (name) => categories.find(cat => cat.name === name);

  // Insert seed entries
  await knex('exercises').insert([
    // 術前期 - 基本動作訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基本動作訓練')?.id,
      name: '階段昇降練習',
      description: '安全な階段の昇り降りを習得し、日常生活での階段使用に備える',
      instructions: '【準備】\n• 手すりのある安全な階段を選択\n• 滑り止めのある適切な靴を着用\n• 初回は理学療法士や家族と一緒に実施\n• 段数は2-3段から開始\n\n【実施方法】\n1. 階段の前に立ち、手すりをしっかりと握ります\n2. 昇り：「健側足から昇る」\n   - 健側足（元気な方の足）を先に一段上に置く\n   - 手すりを使って体を支えながら患側足を同じ段に上げる\n   - 両足が同じ段に揃ったら次の段へ\n3. 降り：「患側足から降りる」\n   - 患側足（手術した方の足）を先に一段下に置く\n   - 手すりでバランスを取りながら健側足を同じ段に下ろす\n   - 両足が揃ったら次の段へ\n\n【コツ】\n• 「昇りは健側から、降りは患側から」を覚える\n• 手すりは常に利き手で握る\n• 急がずに一段ずつ確実に足を置く\n• 上を見上げずに足元に注意を払う\n\n【段階的進歩】\n• Week1-2: 2-3段、手すり+介助\n• Week3-4: 5-7段、手すりのみ\n• Week5以降: 通常の階段、手すり使用\n\n【注意点】\n• 膝に体重をかけた時の痛みに注意\n• バランスを崩しそうになったら無理をしない\n• 疲労時や体調不良時は避ける',
      difficulty_level: 'intermediate',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['必ず手すりを使用', '転倒防止に細心の注意']),
      contraindications: JSON.stringify(['バランス感覚に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 術前期 - 筋力維持
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: '大腿四頭筋セッティング',
      description: '膝を伸ばした状態で太ももの前の筋肉を収縮させる基本的な筋力訓練',
      instructions: '【開始姿勢】\n• 仰向けに寝るか、長座位（足を伸ばして座る）\n• 膝の下にタオルを置いても可\n\n【実施方法】\n1. 膝をピンと真っ直ぐに伸ばします\n2. 太ももの前の筋肉（大腿四頭筋）にぐっと力を入れます\n3. 膝裏でタオルや床を押すイメージで5秒間キープ\n4. 力を抜いてリラックス\n\n【コツ】\n• 太ももの前が硬くなるのを手で触って確認\n• 膝のお皿が上に持ち上がる感覚\n• 呼吸は止めずに自然に',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 15,
      default_duration_seconds: 5,
      rest_time_seconds: 10,
      order_index: 1,
      precautions: JSON.stringify(['痛みの範囲内で実施', '強い痛みがある時は中止']),
      contraindications: JSON.stringify(['急性炎症期', '医師から安静指示がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: 'ハムストリングス強化',
      description: '太ももの裏側の筋肉を強化する運動',
      instructions: '【開始姿勢】\n• うつ伏せに寝ます\n• 枕を腰の下に入れても可\n\n【実施方法】\n1. 片足のかかとをお尻に向けてゆっくり曲げます\n2. 太ももの裏側に力が入るのを感じながら3秒キープ\n3. ゆっくりと元の位置に戻します\n4. 反対の足も同様に行います\n\n【コツ】\n• 腰を反らさないよう注意\n• 太ももは床から浮かせない\n• 膝を曲げる時は勢いをつけずゆっくりと',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 12,
      default_duration_seconds: 3,
      rest_time_seconds: 15,
      order_index: 2,
      precautions: JSON.stringify(['腰痛に注意', '無理な力は入れない']),
      contraindications: JSON.stringify(['腰椎に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: '足首の運動',
      description: '足首の可動域を維持・改善し、血液循環を促進を図る基本的な運動',
      instructions: '【準備】\n• 快適な椅子またはベッドを用意\n\n【開始姿勢】\n• 椅子に座るか、ベッドに仰向けに寝ます\n• 膝は軽く曲げた楽な状態\n• 足首周りの力を抜いてリラックス\n• 足は床から少し浮かせるか、足首が自由に動く位置に\n\n【基本動作】\n1. 背屈・底屈運動：\n   - つま先をゆっくりと天井方向に反らします（背屈）\n   - ふくらはぎが伸びる感覚を確認しながら3秒キープ\n   - つま先をゆっくりと下方向に向けます（底屈）\n   - すねの前が伸びる感覚を確認しながら3秒キープ\n   - この動作を10回繰り返します\n\n2. 内返し・外返し運動：\n   - 足の裏を内側に向けます（内返し）\n   - 足の外側の筋肉の収縮を感じながら3秒キープ\n   - 足の裏を外側に向けます（外返し）\n   - 足の内側の筋肉の収縮を感じながら3秒キープ\n   - この動作を10回繰り返します\n\n3. 円運動：\n   - 足首を中心に大きく円を描くように回します\n   - 時計回りに5回ゆっくりと回します\n   - 反時計回りに5回ゆっくりと回します\n   - 足首の全方向の動きを意識します\n\n【効果とメリット】\n• 足首の可動域維持・改善\n• ふくらはぎの血液循環促進\n• 下肢のむくみ予防・改善\n• 足首周囲筋の筋力維持\n• 深部静脈血栓症の予防\n\n【実施タイミング】\n• 朝起床時の体のウォーミングアップとして\n• 長時間座っている時の合間に\n• 就寝前のリラクゼーションとして\n• 手術後の早期離床前の準備として\n\n【注意とコツ】\n• 痛みのない範囲でゆっくりと動かす\n• 無理に大きく動かそうとしない\n• 動作中は自然な呼吸を続ける\n• 左右の動きの違いがあれば医師に報告',
      difficulty_level: 'beginner',
      default_sets: 2,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 5,
      order_index: 3,
      precautions: JSON.stringify(['痛みがあれば中止', '無理に大きく動かさない']),
      contraindications: JSON.stringify(['足首に外傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 術直後期 - 可動域改善
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: 'ヒールスライド',
      description: 'かかとを滑らせながら膝の屈曲練習を行い、徐々に可動域を回復させる',
      instructions: '【開始姿勢】\n• 仰向けに寝ます\n• 両足を伸ばした状態\n• タオルをかかとの下に敷くと滑りやすい\n\n【実施方法】\n1. 患側（手術した側）の足のかかとを床につけたまま滑らせます\n2. ゆっくりと膝を曲げていきます\n3. 痛みのない範囲で最大まで曲げます\n4. 3秒間その位置を保持\n5. ゆっくりと元の位置に戻します\n\n【注意点】\n• 無理に曲げようとしない\n• 毎日少しずつ曲がる角度を増やす\n• 痛みが増す場合は範囲を狭める',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 1,
      precautions: JSON.stringify(['痛みが強い場合は中止', '無理に曲げない', '腫れが増した場合は休む']),
      contraindications: JSON.stringify(['医師の許可がない場合', '感染の兆候がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: '大腿四頭筋セッティング',
      description: '膝を伸ばした状態で太ももの前の筋肉を収縮させる基本的な筋力訓練',
      instructions: '【開始姿勢】\n• 長座位（足を伸ばして座る）\n• 膝の下にタオルを置いても可\n\n【実施方法】\n1. 膝をピンと真っ直ぐに伸ばします\n2. 太ももの前の筋肉（大腿四頭筋）にぐっと力を入れます\n3. 膝裏でタオルや床を押すイメージで5秒間キープ\n4. 力を抜いてリラックス\n\n【コツ】\n• 太ももの前が硬くなるのを手で触って確認\n• 膝のお皿が上に持ち上がる感覚\n• 呼吸は止めずに自然に',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 15,
      default_duration_seconds: 5,
      rest_time_seconds: 10,
      order_index: 2,
      precautions: JSON.stringify(['痛みの範囲内で実施', '強い痛みがある時は中止']),
      contraindications: JSON.stringify(['急性炎症期', '医師から安静指示がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: '膝蓋骨モビライゼーション',
      description: '膝蓋骨（膝のお皿）を手技で動かして関節の可動性を改善し、周囲組織の柔軟性を向上させる',
      instructions: '【準備】\n• 快適な温度の部屋で実施\n• 手を清潔にし、爪は短く切っておく\n• タオルやクッションで膝を支える準備\n• リラックスできる環境を作る\n\n【開始姿勢】\n• 足を伸ばして座る（長座位）\n• 膝を完全に伸ばした状態にします\n• 膝の下にタオルを敷いてもよい\n• 太ももの筋肉の力を抜いてリラックス\n\n【実施方法】\n1. 膝蓋骨（膝のお皿）の位置を確認します\n2. 両手の親指と人差し指で膝蓋骨の縁を軽く挟みます\n3. 上下方向の動き：\n   - 膝蓋骨を太もも側（上方）に5秒間優しく押します\n   - 膝蓋骨をすね側（下方）に5秒間優しく押します\n4. 左右方向の動き：\n   - 膝蓋骨を外側に5秒間優しく押します\n   - 膝蓋骨を内側に5秒間優しく押します\n5. 斜め方向の動き：\n   - 右上、右下、左上、左下の4方向に各5秒ずつ\n\n【コツとポイント】\n• 膝蓋骨が正常に動く範囲は約1-2cm程度\n• 「優しく」が基本 - 力を入れすぎない\n• 膝蓋骨の下の組織がほぐれる感覚を大切に\n• 太ももの筋肉が緊張していると動きにくいのでリラックス\n• 左右の膝で動きの違いを比較する\n\n【効果】\n• 膝蓋骨周囲の癒着防止\n• 膝関節の滑らかな動きの改善\n• 膝蓋大腿関節の機能改善\n• 周囲組織の血流促進\n• 膝の曲げ伸ばしの準備運動として効果的\n\n【注意点】\n• 強い痛みを感じたら即座に中止\n• 膝蓋骨が不安定に感じる場合は医師に相談\n• 皮膚に傷がある場合は避ける\n• 腫れが著明な場合は軽めに実施',
      difficulty_level: 'beginner',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 5,
      rest_time_seconds: 10,
      order_index: 4,
      precautions: JSON.stringify(['優しく行う', '強い圧迫は避ける']),
      contraindications: JSON.stringify(['膝蓋骨に外傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 術直後期 - 腫脹・疼痛管理
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('腫脹・疼痛管理')?.id,
      name: 'アイシング（冷却療法）',
      description: '術後の腫れと痛みを軽減するための冷却治療',
      instructions: '【準備】\n• 氷嚢または冷却パックを用意\n• タオルで包んで直接肌に触れないようにする\n• タイマーを設定\n• 快適な体勢で座るか横になる\n\n【実施方法】\n1. 膝を軽く曲げた楽な姿勢をとります\n2. タオルで包んだ氷嚢を膝の上に置きます\n3. 15-20分間冷却します\n4. 冷却後は最低1時間空けてから次回実施\n5. 1日3-4回を目安に実施\n\n【効果的な時間帯】\n• 朝起床時\n• 運動後\n• 夜就寝前\n• 痛みや腫れを感じた時\n\n【コツ】\n• 氷嚢の位置を時々調整する\n• 皮膚の色や感覚をチェック\n• 寒すぎる場合はタオルを厚くする\n\n【注意点】\n• 20分以上の連続使用は避ける\n• 皮膚が赤くなりすぎたら中止\n• 循環障害がある場合は医師に相談',
      difficulty_level: 'beginner',
      default_sets: 4,
      default_reps: 1,
      default_duration_seconds: 1200, // 20分
      rest_time_seconds: 3600, // 1時間
      order_index: 1,
      precautions: JSON.stringify(['凍傷に注意', '時間を守る', '皮膚の変化を観察']),
      contraindications: JSON.stringify(['循環障害', '皮膚感覚異常', '寒冷アレルギー']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('腫脹・疼痛管理')?.id,
      name: '挙上（エレベーション）',
      description: '足を心臓より高い位置に上げて腫れを軽減する',
      instructions: '【準備】\n• クッションや枕を2-3個用意\n• ベッドなど快適な場所を選択\n• 読書や音楽など時間を過ごすものを準備\n\n【実施方法】\n1. ベッドに横になります\n2. 患側の足をクッションの上に乗せます\n3. 膝が心臓より10-15cm高くなるように調整\n4. 快適な姿勢を維持したまま30分以上継続\n5. 1日に数回実施します\n\n【最適なタイミング】\n• 食後の休憩時\n• テレビ視聴中\n• 読書時間\n• 就寝前のリラックス時\n\n【効果を高めるコツ】\n• アイシングと組み合わせる\n• 深呼吸やリラクゼーションを併用\n• 足首の軽い運動を追加\n\n【段階的調整】\n• 初期は短時間から開始\n• 快適であれば時間を延長\n• 腫れの程度に応じて頻度を調整',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 1,
      default_duration_seconds: 1800, // 30分
      rest_time_seconds: 0,
      order_index: 2,
      precautions: JSON.stringify(['血流を妨げない程度の高さ', '長時間の同一姿勢を避ける']),
      contraindications: JSON.stringify(['血栓のリスクが高い場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('腫脹・疼痛管理')?.id,
      name: '足首ポンプ運動',
      description: '足首の動きで血液循環を促進し、腫れを軽減する',
      instructions: '【開始姿勢】\n• 椅子に座るか、ベッドに横になります\n• 足を楽な位置に置きます\n• 膝は軽く曲げた状態で\n\n【実施方法】\n1. つま先を天井に向けて足首を反らします（背屈）\n2. 3秒間キープします\n3. つま先を下に向けて足首を伸ばします（底屈）\n4. 3秒間キープします\n5. この動作を繰り返します\n\n【応用バリエーション】\n• 足指のグーパー運動\n• ふくらはぎの軽いマッサージ\n• 両足同時の運動\n\n【実施頻度】\n• 1時間に1回程度\n• 長時間座っている時は特に重要\n• 就寝前と起床時に実施\n\n【効果】\n• 血液循環の改善\n• むくみの軽減\n• 血栓予防\n• 筋肉の柔軟性維持',
      difficulty_level: 'beginner',
      default_sets: 5,
      default_reps: 20,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 3,
      precautions: JSON.stringify(['痛みのない範囲で実施', '無理な動きは避ける']),
      contraindications: JSON.stringify(['足首に外傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 基礎回復期 - 歩行訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '正常歩行練習',
      description: '正しい歩き方を意識して歩行パターンを改善する',
      instructions: '【準備】\n• 平らで滑らない場所で実施\n• 10-20メートルの歩行距離を確保\n• 必要に応じて杖や手すりを使用\n\n【実施方法】\n1. まず正しい立位姿勢を作ります\n2. 健側足から歩き始めます\n3. かかとから着地し、つま先で蹴り出します\n4. 歩幅は左右同じになるよう意識\n5. 膝は真っ直ぐ前に向けて歩きます\n\n【チェックポイント】\n• 上体がまっすぐ\n• 腕の振りが自然\n• 足音が左右同じ',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 1,
      default_duration_seconds: 60,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['転倒防止', '疲労に注意', '痛みがあれば休憩']),
      contraindications: JSON.stringify(['荷重制限がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '片脚立位',
      description: '患側での片脚立位練習でバランス能力を向上させる',
      instructions: '【準備】\n• 安全な場所で実施\n• 壁や手すりの近くに立つ\n• 必要に応じて支えを使用\n\n【実施方法】\n1. 両足で安定して立ちます\n2. 健側足をゆっくり床から離します\n3. 患側足一本でバランスを取ります\n4. 目標時間まで維持します\n5. 慣れてきたら目を閉じて挑戦\n\n【段階的進歩】\n• 最初は5秒から開始\n• 徐々に30秒まで延長\n• 手の支えなしで実施',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 5,
      default_duration_seconds: 10,
      rest_time_seconds: 30,
      order_index: 2,
      precautions: JSON.stringify(['転倒防止', '支持物の準備', '無理をしない']),
      contraindications: JSON.stringify(['著明な不安定性', '平衡感覚障害']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '階段昇降（基礎）',
      description: '手すりを使用した安全な階段昇降の練習',
      instructions: '【準備】\n• 手すりがある階段で実施\n• 滑り止めのある靴を着用\n• 介助者がいると安心\n\n【昇る時の方法】\n1. 健側足を先に一段上に置きます\n2. 手すりを握りながら体重を移します\n3. 患側足を同じ段に置きます\n4. 一段ずつ確実に昇ります\n\n【降りる時の方法】\n1. 患側足を先に一段下に置きます\n2. 手すりでしっかり支えながら\n3. 健側足を同じ段に置きます\n\n【覚え方】\n昇りは「良い足から」、降りは「悪い足から」',
      difficulty_level: 'intermediate',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 3,
      precautions: JSON.stringify(['必ず手すりを使用', '転倒防止', '一段ずつ確実に']),
      contraindications: JSON.stringify(['バランス感覚に問題がある場合', '膝の痛みが強い場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 基礎回復期 - 基礎筋力強化
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基礎筋力強化')?.id,
      name: '大腿四頭筋セッティング（長座位）',
      description: '長座位でタオルを膝下に置いて潰すことで大腿四頭筋を強化する運動',
      instructions: '【準備】\n• ベッドまたは床に座れる環境を用意\n• 厚手のタオルを1枚用意\n• 両足を真っ直ぐ前に伸ばせるスペースを確保\n\n【開始姿勢】\n• 床またはベッドに長座位（足を伸ばして座る）になります\n• 患側の膝の下にタオルを丸めて置きます\n• 背筋を伸ばし、両手は体の後ろについて体を支えます\n• 両足は真っ直ぐ前に伸ばします\n\n【実施方法】\n1. 患側の大腿四頭筋（太ももの前）に力を入れます\n2. 膝裏でタオルを床に向かって強く押しつぶします\n3. 膝のお皿が上に持ち上がる感覚を確認\n4. 5秒間しっかりとタオルを潰し続けます\n5. ゆっくりと力を抜いてリラックス\n6. 健側も同様に実施します\n\n【コツとポイント】\n• 太ももの前の筋肉が硬くなるのを手で触って確認\n• 膝のお皿（膝蓋骨）が上方に移動する感覚\n• タオルがしっかり潰れるまで力を入れる\n• 足首は軽く背屈（つま先を上に向ける）\n• 呼吸は止めずに自然に続ける\n\n【段階的進歩】\n• Week1-2: 薄いタオルから開始\n• Week3-4: 厚いタオルで強い収縮\n• Week5以降: 保持時間を7-10秒まで延長\n\n【効果】\n• 大腿四頭筋の筋力向上\n• 膝関節の安定性改善\n• 筋萎縮の予防\n• 膝伸展機能の回復',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 5,
      rest_time_seconds: 30,
      order_index: 1,
      precautions: JSON.stringify(['膝の痛みに注意', '無理な荷重は避ける']),
      contraindications: JSON.stringify(['急性期の炎症', '医師の荷重制限がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基礎筋力強化')?.id,
      name: 'SLR（ストレートレッグレイズ）',
      description: '膝を伸ばしたまま足を上げることで大腿四頭筋と股関節屈筋を強化する運動',
      instructions: '【準備】\n• 平らで硬い床またはベッドを使用\n• マットやタオルを敷いて快適にする\n• 膝が曲がらないよう意識を集中\n\n【開始姿勢】\n• 仰向けに寝ます\n• 健側の膝は90度に曲げて足裏を床につけます\n• 患側の足は真っ直ぐ伸ばして床につけます\n• 両手は体の横に置いて体を安定させます\n\n【実施方法】\n1. 患側の膝を完全に伸ばしたまま維持します\n2. 大腿四頭筋（太ももの前）に力を入れます\n3. 膝が曲がらないよう注意しながら足全体をゆっくり持ち上げます\n4. 健側の膝の高さまで上げます（約30-45度）\n5. 3秒間その位置でキープします\n6. ゆっくりと制御しながら元の位置に戻します\n7. 床につく直前で次の動作を開始します\n\n【重要なポイント】\n• 膝は絶対に曲げない（ストレートを維持）\n• 太ももの前の筋肉を常に収縮させる\n• 足首は軽く背屈（つま先を上に向ける）\n• 腰を反らせないよう注意\n• 動作は全てゆっくりと制御して行う\n\n【段階的進歩】\n• Week1-2: 膝伸展位の維持に集中\n• Week3-4: 挙上角度を徐々に上げる\n• Week5以降: 保持時間を5秒まで延長\n\n【効果】\n• 大腿四頭筋の筋力向上\n• 股関節屈筋の強化\n• 膝伸展機能の改善\n• 歩行時の脚の振り出し能力向上\n\n【注意点】\n• 膝が曲がってしまう場合は無理をしない\n• 腰痛を感じたら中止する\n• 挙上角度は痛みのない範囲で調整',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 2,
      precautions: JSON.stringify(['膝が曲がらないよう注意', '腰を反らせない', '無理な挙上は避ける']),
      contraindications: JSON.stringify(['腰痛がある場合', '股関節に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基礎筋力強化')?.id,
      name: '股関節外転運動（側臥位）',
      description: '側臥位で足を横に上げることで中臀筋を強化し、歩行時の骨盤安定性を向上させる運動',
      instructions: '【準備】\n• マットまたは柔らかい床面を用意\n• 枕やクッションで頭を支える\n• 快適に横になれるスペースを確保\n\n【開始姿勢】\n• 健側を下にして横向きに寝ます\n• 下の手で頭を支えるか、枕を使用\n• 上の手は胸の前に置いて体を安定させます\n• 両足は真っ直ぐ伸ばします\n• 体は一直線を保ちます\n\n【実施方法】\n1. 患側（上側）の足を真っ直ぐ伸ばしたまま維持\n2. 足全体を真横にゆっくりと持ち上げます\n3. 床から30-45度程度まで上げます\n4. 3秒間その位置でキープします\n5. お尻の横の筋肉（中臀筋）の収縮を意識\n6. ゆっくりと制御しながら元の位置に戻します\n7. 足同士が触れる直前で次の動作を開始\n\n【重要なポイント】\n• 足は真横に上げる（前後に振らない）\n• 膝は真っ直ぐ伸ばしたまま\n• 体は常に一直線を保つ\n• 骨盤が前後に傾かないよう注意\n• お尻の横の筋肉を意識する\n\n【段階的進歩】\n• Week1-2: 小さな角度から開始（15-20度）\n• Week3-4: 角度を徐々に上げる（30-45度）\n• Week5以降: 保持時間を5秒まで延長\n\n【効果】\n• 中臀筋の筋力向上\n• 骨盤安定性の改善\n• 歩行時の体幹安定性向上\n• 膝関節への負担軽減\n\n【注意点】\n• 腰を反らせない\n• 勢いをつけて上げない\n• 痛みがあれば角度を調整',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 12,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 3,
      precautions: JSON.stringify(['腰を反らせない', '勢いをつけない', '痛みのない範囲で実施']),
      contraindications: JSON.stringify(['股関節に問題がある場合', '腰痛がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基礎筋力強化')?.id,
      name: 'クラムシェル',
      description: '側臥位で膝を開く動作により深層外旋筋群を強化し、股関節の安定性を向上させる運動',
      instructions: '【準備】\n• マットまたは柔らかい床面を用意\n• 枕やクッションで頭を支える\n• 快適に横になれるスペースを確保\n\n【開始姿勢】\n• 健側を下にして横向きに寝ます\n• 頭を下の腕または枕で支えます\n• 上の手は胸の前に置いて体を安定させます\n• 両膝を約90度曲げて重ねます\n• 足首も重ねて体は一直線を保ちます\n\n【実施方法】\n1. 足首は重ねたまま、患側（上側）の膝だけを開きます\n2. 貝殻が開くように膝をゆっくりと上に持ち上げます\n3. 可能な範囲まで開いて3秒間キープします\n4. お尻の奥の筋肉（深層外旋筋）の収縮を意識\n5. ゆっくりと制御しながら元の位置に戻します\n6. 膝同士が触れる直前で次の動作を開始\n\n【重要なポイント】\n• 足首は常に重ねたまま\n• 骨盤が前後に倒れないよう注意\n• 体幹は常に安定させる\n• 膝を開く時は股関節から動かす\n• お尻の奥の筋肉を意識する\n\n【段階的進歩】\n• Week1-2: 小さな開き角度から開始\n• Week3-4: 開き角度を徐々に大きくする\n• Week5以降: 保持時間を5秒まで延長\n\n【効果】\n• 深層外旋筋群の強化\n• 股関節の安定性向上\n• 骨盤の安定性改善\n• 膝関節への負担軽減\n\n【注意点】\n• 腰を反らせない\n• 勢いをつけて開かない\n• 痛みがあれば開き角度を調整',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 15,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 4,
      precautions: JSON.stringify(['骨盤の安定を保つ', '勢いをつけない', '痛みのない範囲で実施']),
      contraindications: JSON.stringify(['股関節に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基礎筋力強化')?.id,
      name: '股関節伸展運動（腹臥位）',
      description: '腹臥位で足を後ろに上げることで大臀筋を強化し、歩行時の推進力を向上させる運動',
      instructions: '【準備】\n• マットまたは柔らかい床面を用意\n• 枕やクッションで額を支える\n• うつ伏せになれるスペースを確保\n\n【開始姿勢】\n• うつ伏せに寝ます\n• 額の下に枕やクッションを置きます\n• 両腕は体の横に置くか、額の下で組みます\n• 両足は真っ直ぐ伸ばします\n• 腰は平らに保ちます\n\n【実施方法】\n1. 患側の足を膝を伸ばしたまま維持します\n2. お尻の筋肉（大臀筋）に力を入れます\n3. 足全体を床からゆっくりと持ち上げます\n4. 15-20度程度まで上げて3秒間キープします\n5. お尻の筋肉の収縮を強く意識します\n6. ゆっくりと制御しながら元の位置に戻します\n7. 床につく直前で次の動作を開始\n\n【重要なポイント】\n• 膝は真っ直ぐ伸ばしたまま\n• 腰を反らせすぎない\n• お尻の筋肉を主動筋として使う\n• 骨盤が浮かないよう注意\n• 動作は全てゆっくりと制御\n\n【段階的進歩】\n• Week1-2: 小さな挙上角度から開始（5-10度）\n• Week3-4: 角度を徐々に上げる（15-20度）\n• Week5以降: 保持時間を5秒まで延長\n\n【効果】\n• 大臀筋の筋力向上\n• 歩行時の推進力改善\n• 股関節伸展機能の向上\n• 腰部安定性の改善\n\n【注意点】\n• 腰痛を感じたら中止\n• 無理に高く上げない\n• 挙上角度は痛みのない範囲で調整',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 12,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 5,
      precautions: JSON.stringify(['腰を反らせすぎない', '無理な挙上は避ける', '腰痛に注意']),
      contraindications: JSON.stringify(['腰痛がある場合', '腰椎に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基礎筋力強化')?.id,
      name: 'ミニスクワット',
      description: '膝屈曲30度までの浅いスクワットで安全に筋力強化',
      instructions: '【準備】\n• 平らで滑らない床面で実施\n• 滑り止めのある靴を着用\n• 必要に応じて壁や手すりを近くに配置\n• 十分なスペースを確保\n\n【開始姿勢】\n• 足を肩幅に開いて立ちます\n• つま先は軽く外向きにします\n• 手は腰に当てるか前に伸ばします\n• 上体はまっすぐに保ちます\n• 重心は両足の中央に置きます\n\n【実施方法】\n1. ゆっくりと膝を曲げ始めます\n2. 膝の角度が30度程度（浅く座る程度）まで曲げます\n3. その位置で3秒間キープします\n4. ゆっくりと元の立位に戻します\n5. 膝がつま先より前に出ないよう注意\n6. 上体は軽く前傾させます\n\n【重要なポイント】\n• 深く曲げすぎない（30度まで）\n• 膝とつま先の向きを揃える\n• 重心はかかと寄りに保つ\n• 呼吸を止めずに自然に続ける\n• 動作はゆっくりと制御して行う\n\n【段階的進歩】\n• Week1-2: 15-20度の浅い角度から開始\n• Week3-4: 30度まで深くする\n• Week5以降: 保持時間を5秒まで延長\n\n【効果】\n• 大腿四頭筋の基礎筋力向上\n• 膝関節周囲筋の協調性改善\n• 日常生活動作の準備\n• バランス能力の向上\n\n【注意点】\n• 膝がつま先より前に出ない\n• 痛みのない範囲で実施\n• 深く曲げすぎない',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 45,
      order_index: 6,
      precautions: JSON.stringify(['膝がつま先より前に出ない', '痛みのない範囲', '浅い角度から開始']),
      contraindications: JSON.stringify(['膝蓋大腿関節症状が強い場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 筋力強化期 - 筋力強化
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: '大腿四頭筋セッティング（長座位）',
      description: '長座位でタオルを膝下に置いて潰すことで大腿四頭筋を強化する運動（基礎回復期からの継続）',
      instructions: '【準備】\n• ベッドまたは床に座れる環境を用意\n• 厚手のタオルを1枚用意\n• 背もたれがあると楽です\n• 両足を真っ直ぐ前に伸ばせるスペースを確保\n\n【開始姿勢】\n• 床またはベッドに長座位（足を伸ばして座る）になります\n• 患側の膝の下にタオルを丸めて置きます\n• 背筋を伸ばし、両手は体の後ろについて体を支えます\n• 両足は真っ直ぐ前に伸ばします\n\n【実施方法】\n1. 患側の大腿四頭筋（太ももの前）に力を入れます\n2. 膝裏でタオルを床に向かって強く押しつぶします\n3. 膝のお皿が上に持ち上がる感覚を確認\n4. 7秒間しっかりとタオルを潰し続けます（基礎期より延長）\n5. ゆっくりと力を抜いてリラックス\n6. 健側も同様に実施します\n\n【段階的進歩（筋力強化期）】\n• より厚いタオルを使用\n• 保持時間を10秒まで延長\n• より強い収縮力を意識\n\n【効果】\n• 大腿四頭筋の筋力向上\n• 膝関節の安定性改善\n• 筋萎縮の予防\n• 膝伸展機能の回復',
      difficulty_level: 'intermediate',
      default_sets: 4,
      default_reps: 12,
      default_duration_seconds: 7,
      rest_time_seconds: 15,
      order_index: 1,
      precautions: JSON.stringify(['痛みの範囲内で実施', '強い痛みがある時は中止']),
      contraindications: JSON.stringify(['急性炎症期', '医師から安静指示がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: '股関節外転運動（側臥位）',
      description: '側臥位で足を横に上げることで中臀筋を強化し、歩行時の骨盤安定性を向上させる運動（基礎回復期からの継続）',
      instructions: '【準備】\n• マットまたは柔らかい床面を用意\n• 枕やクッションで頭を支える\n• 快適に横になれるスペースを確保\n\n【開始姿勢】\n• 健側を下にして横向きに寝ます\n• 下の手で頭を支えるか、枕を使用\n• 上の手は胸の前に置いて体を安定させます\n• 両足は真っ直ぐ伸ばします\n• 体は一直線を保ちます\n\n【実施方法】\n1. 患側（上側）の足を真っ直ぐ伸ばしたまま維持\n2. 足全体を真横にゆっくりと持ち上げます\n3. 床から45-60度程度まで上げます（基礎期より高角度）\n4. 5秒間その位置でキープします（基礎期より延長）\n5. お尻の横の筋肉（中臀筋）の収縮を意識\n6. ゆっくりと制御しながら元の位置に戻します\n\n【段階的進歩（筋力強化期）】\n• より高い角度での挙上\n• 保持時間の延長\n• より強い筋収縮を意識\n\n【効果】\n• 中臀筋の筋力向上\n• 骨盤安定性の改善\n• 歩行時の体幹安定性向上\n• 膝関節への負担軽減',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 15,
      default_duration_seconds: 5,
      rest_time_seconds: 30,
      order_index: 2,
      precautions: JSON.stringify(['腰を反らせない', '勢いをつけない', '痛みのない範囲で実施']),
      contraindications: JSON.stringify(['股関節に問題がある場合', '腰痛がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: '股関節伸展運動（腹臥位）',
      description: '腹臥位で足を後ろに上げることで大臀筋を強化し、歩行時の推進力を向上させる運動（基礎回復期からの継続）',
      instructions: '【準備】\n• マットまたは柔らかい床面を用意\n• 枕やクッションで額を支える\n• うつ伏せになれるスペースを確保\n\n【開始姿勢】\n• うつ伏せに寝ます\n• 額の下に枕やクッションを置きます\n• 両腕は体の横に置くか、額の下で組みます\n• 両足は真っ直ぐ伸ばします\n• 腰は平らに保ちます\n\n【実施方法】\n1. 患側の足を膝を伸ばしたまま維持します\n2. お尻の筋肉（大臀筋）に力を入れます\n3. 足全体を床からゆっくりと持ち上げます\n4. 20-30度程度まで上げて5秒間キープします（基礎期より高角度・長時間）\n5. お尻の筋肉の収縮を強く意識します\n6. ゆっくりと制御しながら元の位置に戻します\n\n【段階的進歩（筋力強化期）】\n• より高い挙上角度\n• 保持時間の延長\n• より強い筋収縮を意識\n\n【効果】\n• 大臀筋の筋力向上\n• 歩行時の推進力改善\n• 股関節伸展機能の向上\n• 腰部安定性の改善',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 15,
      default_duration_seconds: 5,
      rest_time_seconds: 30,
      order_index: 3,
      precautions: JSON.stringify(['腰を反らせすぎない', '無理な挙上は避ける', '腰痛に注意']),
      contraindications: JSON.stringify(['腰痛がある場合', '腰椎に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'ブラジリアンスクワット',
      description: '後足を台に乗せて行う片足スクワットで、より高強度な下肢筋力強化を図る運動',
      instructions: '【準備】\n• 高さ40-50cmの安定した台またはベンチを用意\n• 滑り止めのある靴を着用\n• 必要に応じて手すりなど支えを近くに配置\n• 十分な前後スペースを確保\n\n【開始姿勢】\n• 台から約60-80cm前方に立ちます\n• 患側を前足、健側を後足とします\n• 後足（健側）の足背を台の上に乗せます\n• 前足（患側）に体重の約70%をかけます\n• 上体はまっすぐに保ちます\n\n【実施方法】\n1. 前足（患側）に重心を置いたまま維持します\n2. 前足の膝をゆっくりと45度まで曲げていきます\n3. 膝がつま先より前に出ないよう注意します\n4. 最下点で2秒間キープします\n5. 前足で床を押して元の位置に戻ります\n6. 動作中は上体を安定させます\n\n【重要なポイント】\n• 前足（患側）が主働筋\n• 後足は軽く支える程度\n• 膝の向きとつま先の向きを揃える\n• 上体が前に倒れすぎないよう注意\n• 膝屈曲は45度まで（深すぎない）\n\n【段階的進歩】\n• Week1-2: 30度の膝屈曲から開始\n• Week3-4: 45度まで深く曲げる\n• Week5以降: 負荷を追加（ダンベル等）\n\n【効果】\n• 大腿四頭筋の高強度強化\n• 片足での機能的筋力向上\n• バランス能力の向上\n• 日常生活動作の改善',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 2,
      rest_time_seconds: 60,
      order_index: 4,
      precautions: JSON.stringify(['膝屈曲は45度まで', '前足に体重を集中', 'バランスを崩したら中止']),
      contraindications: JSON.stringify(['膝に不安定性がある場合', '重度の膝痛がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'ドロップスクワット',
      description: '台から降りる動作と同時にスクワットを行い、着地時の制御力と筋力を向上させる運動',
      instructions: '【準備】\n• 高さ15-20cmの安定した台を用意\n• 滑り止めのある靴を着用\n• 十分な前方スペースを確保\n• 最初は低い台から開始\n\n【開始姿勢】\n• 台の上に両足で立ちます\n• 足は肩幅程度に開きます\n• つま先は軽く外向きにします\n• 上体はまっすぐに保ちます\n• 両手は胸の前で組むか腰に当てます\n\n【実施方法】\n1. 台の前方に向かって両足で同時に降ります\n2. 着地と同時に膝を45度まで曲げてスクワット姿勢をとります\n3. 着地の衝撃を膝とお尻で吸収します\n4. 2秒間スクワット姿勢をキープします\n5. ゆっくりと立ち上がって元の立位に戻ります\n6. 台に戻って次の動作を繰り返します\n\n【重要なポイント】\n• 着地は足裏全体で行う\n• 膝とつま先の向きを揃える\n• 着地音を小さくするよう意識\n• 膝が内側に入らないよう注意\n• 上体が前に倒れすぎないよう維持\n\n【段階的進歩】\n• Week1-2: 低い台（10-15cm）から開始\n• Week3-4: 台の高さを上げる（20-25cm）\n• Week5以降: 片足での実施に挑戦\n\n【効果】\n• 着地時の制御力向上\n• 大腿四頭筋の遠心性収縮強化\n• 膝関節の安定性向上\n• 衝撃吸収能力の改善\n\n【注意点】\n• 着地時の膝の痛みに注意\n• 高すぎる台は避ける\n• バランスを崩したら無理をしない',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 2,
      rest_time_seconds: 90,
      order_index: 5,
      precautions: JSON.stringify(['着地の衝撃に注意', '膝の痛みがあれば中止', '適切な台の高さを選択']),
      contraindications: JSON.stringify(['膝に不安定性がある場合', '着地時に痛みがある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'フォワードランジ（膝屈曲45度）',
      description: '前方に踏み出すランジ動作を膝屈曲45度に制限して安全に行う機能的筋力強化運動',
      instructions: '【準備】\n• 平らで滑らない床面で実施\n• 滑り止めのある靴を着用\n• 前後に十分なスペースを確保\n• 必要に応じて手すりなど支えを近くに配置\n\n【開始姿勢】\n• 足を肩幅程度に開いて立ちます\n• 両手は腰に当てるか胸の前で組みます\n• 上体はまっすぐに保ちます\n• 重心は両足の中央に置きます\n\n【実施方法】\n1. 患側足を前方に大きく踏み出します（歩幅約80cm）\n2. 前足に体重をかけながら膝を45度まで曲げます\n3. 後ろ足の膝は床に近づけますが触れません\n4. 前足の膝がつま先より前に出ないよう注意\n5. 2秒間その姿勢をキープします\n6. 前足で床を押して元の立位に戻ります\n\n【重要なポイント】\n• 膝屈曲は45度まで（深すぎない）\n• 前足の膝とつま先の向きを揃える\n• 上体は垂直を保つ\n• 体重は前足に70%、後足に30%\n• 動作はゆっくりと制御して行う\n\n【段階的進歩】\n• Week1-2: 浅いランジ（30度屈曲）から開始\n• Week3-4: 45度屈曲まで深くする\n• Week5以降: ダイナミックな動作に発展\n\n【効果】\n• 機能的な下肢筋力向上\n• 片足での安定性改善\n• 歩行やスポーツ動作の準備\n• バランス能力の向上\n\n【注意点】\n• 膝屈曲角度を守る（45度まで）\n• 膝の内側への倒れ込みを防ぐ\n• バランスを崩したら無理をしない',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 2,
      rest_time_seconds: 45,
      order_index: 6,
      precautions: JSON.stringify(['膝屈曲は45度まで', '膝の向きに注意', 'バランス維持を重視']),
      contraindications: JSON.stringify(['膝に不安定性がある場合', '重度の膝痛がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 筋力強化期 - バランス訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('バランス訓練')?.id,
      name: 'バランスボード',
      description: '不安定面での立位バランス訓練により、膝関節の安定性と固有受容感覚を向上させる',
      instructions: '【準備】\n• バランスボードまたはクッションを用意\n• 壁や手すりなど支えとなるものを近くに設置\n• 滑り止めのある靴を着用\n• 必要に応じて介助者に立ち会ってもらう\n\n【実施方法】\n1. 最初は両手で壁や手すりを軽く支えながらバランスボードに立ちます\n2. 両足を肩幅程度に開いて重心を中央に保ちます\n3. ボードが水平になるようにバランスを調整します\n4. 安定したら10-30秒間その姿勢を維持します\n5. 慣れてきたら手の支えを徐々に減らします\n\n【段階的進歩】\n• Level 1: 両手支持で両足立位\n• Level 2: 片手支持で両足立位\n• Level 3: 支持なしで両足立位\n• Level 4: 支持なしで片足立位\n• Level 5: 目を閉じてのバランス訓練\n\n【応用練習】\n• ボールキャッチをしながらバランス保持\n• 上半身の軽い運動を併用\n• 左右への重心移動練習\n\n【効果】\n• 膝関節周囲筋の協調性向上\n• 固有受容感覚の改善\n• 動的安定性の向上\n• 転倒予防能力の強化\n\n【安全のコツ】\n• 無理をせず段階的に進める\n• バランスを崩したらすぐに支えを使う\n• 疲労時は避ける',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 1,
      default_duration_seconds: 30,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['転倒防止対策', '段階的に難易度アップ']),
      contraindications: JSON.stringify(['重度のバランス障害']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('バランス訓練')?.id,
      name: '片足立位練習',
      description: '患側での片足立位によるバランス能力と筋力の向上',
      instructions: '【準備】\n• 壁や手すりなど支えの近くで実施\n• 平らで滑らない床面を選択\n• 時計またはタイマーを用意して時間を測定\n\n【実施方法】\n1. 良い姿勢で両足立位を取ります\n2. 両手は腰に当てるか、軽く支えを持ちます\n3. 健側足をゆっくりと床から離します\n4. 患側足のみでバランスを保ちます\n5. 目標時間まで維持し、ゆっくりと両足をつきます\n\n【時間の目標設定】\n• Week 1-2: 5-10秒\n• Week 3-4: 15-20秒\n• Week 5-6: 30秒以上\n• 最終目標: 60秒の維持\n\n【難易度調整】\n• 易しい: 両手で壁を支えながら\n• 標準: 片手で軽く支えながら\n• 難しい: 支えなしで実施\n• 最高難度: 目を閉じて実施\n\n【コツとポイント】\n• 立位足の膝を軽く曲げて安定性を保つ\n• 視線は正面の一点を見つめる\n• 体の軸を真っ直ぐに保つ\n• 浮かせた足は力を抜いてリラックス\n\n【バランスを崩した時】\n• 無理をせずにすぐに両足をつく\n• 壁や手すりを利用する\n• 休憩してから再度挑戦',
      difficulty_level: 'intermediate',
      default_sets: 4,
      default_reps: 3,
      default_duration_seconds: 15,
      rest_time_seconds: 30,
      order_index: 2,
      precautions: JSON.stringify(['転倒防止', '無理をしない', '支えをすぐ使えるようにする']),
      contraindications: JSON.stringify(['重度のバランス障害', '患側に痛みがある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'スクワット（膝屈曲60°）',
      description: '膝屈曲60度までの深いスクワットで大腿四頭筋とハムストリングスの筋力を強化する上級運動',
      instructions: '【準備】\n• 平らで滑らない床面を選択\n• 鏡があれば正面に設置して動作確認\n• 必要に応じて軽い重りやダンベルを用意\n• 周囲に十分なスペースを確保\n• 壁や椅子を近くに置いて安全対策\n\n【開始姿勢】\n• 足を肩幅程度に開いて立ちます\n• つま先はやや外向きにします（15-30度程度）\n• 背筋を伸ばし、胸を張ります\n• 腕は胸の前で組むか、前方に伸ばします\n• 重心は両足の中央に置きます\n\n【実施方法】\n1. ゆっくりと股関節から曲げ始めます\n2. 膝も同時に曲げながら、お尻を後ろに引くように下がります\n3. 膝の角度が60度になるまで下降します（太ももが床と30度の角度）\n4. 膝がつま先より前に出ないよう注意します\n5. 最下点で1-2秒間姿勢を保持します\n6. 踵に体重をかけながら、股関節と膝を同時に伸ばして立ち上がります\n7. 立ち上がりは下降よりもやや速めに行います\n\n【正しいフォームのチェックポイント】\n• 膝とつま先の向きが一致している\n• 膝がつま先より前に出ていない\n• 背中が丸まっていない\n• 重心が踵寄りに保たれている\n• 下降と上昇の動作が制御されている\n\n【段階的進歩】\n• Week 1-2: 体重のみで正確なフォーム習得\n• Week 3-4: 回数増加（8-12回）\n• Week 5-6: 軽い重りを持って実施\n• Week 7以降: 重量増加または片足スクワットへ発展\n\n【筋力強化のポイント】\n• 下降時は3-4秒かけてゆっくりと\n• 最下点で1-2秒間の静止\n• 立ち上がりは2-3秒で制御して\n• 呼吸は下降時に吸い、上昇時に吐く\n\n【安全上の注意】\n• ミニスクワット（30度）で十分な筋力がついてから実施\n• 膝に痛みを感じたら即座に中止\n• 正しいフォームを優先し、無理に深く曲げない\n• 疲労時は浅い角度に調整\n\n【効果】\n• 大腿四頭筋の大幅な筋力向上\n• ハムストリングス・大臀筋の強化\n• 機能的な動作パターンの習得\n• スポーツ復帰に向けた基礎筋力構築',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 3,
      precautions: JSON.stringify(['膝屈曲は60度まで', '正しいフォーム優先', '痛みがあれば中止', '段階的な負荷増加']),
      contraindications: JSON.stringify(['膝に不安定性がある場合', '重度の膝痛', 'ミニスクワットができない場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 機能訓練期 - スポーツ動作訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: '両足ジャンプ着地',
      description: '安全で正しい着地技術を習得するための基本的なジャンプ練習',
      instructions: '【準備】\n• 平らで滑らない床で実施\n• 運動靴を着用\n• 十分なスペースを確保\n\n【実施方法】\n1. 足を肩幅に開いて立ちます\n2. 軽く膝を曲げて、垂直に15-20cm程度ジャンプします\n3. 着地時は以下に注意：\n   - 足裏全体で着地\n   - 膝を軽く曲げてクッション性を保つ\n   - 膝とつま先の向きを揃える\n   - 上体はやや前傾\n4. 着地後2-3秒間バランスを保持\n\n【段階的進歩】\n• 最初は低いジャンプから開始\n• 慣れてきたら高さを上げる\n• 目を閉じて着地バランスに挑戦',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 3,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['適切な着地フォーム', '膝の内側への倒れ込み（Knee in）を避ける', '着地音を小さくする']),
      contraindications: JSON.stringify(['膝の不安定性が残存', '痛みがある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: '片足ジャンプ着地',
      description: '競技復帰に向けた高度な片足ジャンプと着地の練習',
      instructions: '【準備】\n• 両足ジャンプが安全にできることを確認\n• 安全な環境で実施\n\n【実施方法】\n1. 患側足で立ちます\n2. 軽く膝を曲げて前方に15cm程度ジャンプ\n3. 同じ足で着地します\n4. 着地のポイント：\n   - 膝を適度に曲げて衝撃を吸収\n   - 膝が内側に入らないよう注意\n   - 着地後3秒間バランス保持\n5. 健側足でも同様に実施\n\n【バリエーション】\n• 前後方向のジャンプ\n• 左右方向のジャンプ\n• 連続ジャンプ（2-3回）',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 5,
      default_duration_seconds: 3,
      rest_time_seconds: 90,
      order_index: 2,
      precautions: JSON.stringify(['十分な筋力がついてから実施', '膝の安定性を確認', '無理をしない']),
      contraindications: JSON.stringify(['膝の痛みや腫れがある場合', '筋力が不十分な場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: 'ボックスステップアップ',
      description: '段差を使った実用的な動作訓練',
      instructions: '【準備】\n• 高さ15-30cmの安定した台やステップを用意\n• 滑り止めのある靴を着用\n• 手すりや支えがあると安心\n\n【実施方法】\n1. 台の前に立ちます\n2. 患側足を台の上に置きます\n3. 体重を患側足に移しながら台に上がります\n4. 両足が台の上に揃ったら一旦停止\n5. ゆっくりと同じ順序で降ります\n\n【ポイント】\n• 膝がつま先より前に出ないよう注意\n• 上体を軽く前傾させて重心を安定\n• 勢いをつけずにコントロールして実施\n\n【段階的進歩】\n• 低い台から始めて徐々に高くする\n• 慣れてきたら手の支えなしで実施',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 0,
      rest_time_seconds: 45,
      order_index: 3,
      precautions: JSON.stringify(['台の安定性を確認', '転倒に注意', '膝の位置に注意']),
      contraindications: JSON.stringify(['バランス感覚に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: 'フォワードランジ',
      description: '前方への大きな一歩と膝の安定性を強化する運動',
      instructions: '【開始姿勢】\n• 足を肩幅程度に開いて立ちます\n• 両手は腰に当てるか胸の前で組む\n\n【実施方法】\n1. 患側足を大きく前方に踏み出します（歩幅は約60-90cm）\n2. 前足に体重をかけながら膝を90度まで曲げます\n3. 後ろ足の膝は床に近づけますが触れません\n4. 前足で床を押して元の立位に戻ります\n5. 反対の足でも同様に実施\n\n【注意点】\n• 前に出した膝がつま先より前に出ない\n• 上体は真っ直ぐ保つ\n• バランスを崩さないよう慎重に\n\n【効果】\n• 太ももとお尻の筋力強化\n• 膝関節の安定性向上\n• バランス能力の向上',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 3,
      rest_time_seconds: 60,
      order_index: 4,
      precautions: JSON.stringify(['膝の位置に注意', 'バランスを崩さない', '深く曲げすぎない']),
      contraindications: JSON.stringify(['膝に痛みがある場合', '腰痛がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 機能訓練期 - アジリティ訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'ラテラルステップ（基礎）',
      description: '横方向への安全なステップ移動の練習',
      instructions: '【準備】\n• 3-4メートルの直線距離を確保\n• 床に目印となるマーカーやテープを置く\n• 滑りにくい靴を着用\n\n【実施方法】\n1. 足を肩幅に開いて立ちます\n2. 膝を軽く曲げた姿勢を保ちます\n3. 右方向に移動する場合：\n   - 右足を横に一歩踏み出します\n   - 左足を右足に近づけます\n   - 足が揃ったら再び右足を踏み出します\n4. 3-4歩移動したら左方向に同様に実施\n\n【ポイント】\n• 膝とつま先の向きを常に揃える\n• 上体は真っ直ぐ保つ\n• 最初はゆっくり、慣れてきたらスピードアップ\n\n【段階的進歩】\n• ゆっくりから中程度のスピードへ\n• 移動距離を徐々に延ばす',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 0,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['膝の内側への倒れ込みを避ける', '適切なフォーム維持', '転倒に注意']),
      contraindications: JSON.stringify(['膝の痛みがある場合', 'バランス感覚に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'ジグザグ歩行',
      description: '方向転換能力を向上させるジグザグパターンでの歩行練習',
      instructions: '【準備】\n• コーンやマーカーを5個、約2メートル間隔でジグザグに配置\n• 安全な靴を着用\n• 十分なスペースを確保\n\n【実施方法】\n1. スタート地点に立ちます\n2. 最初のマーカーに向かって歩きます\n3. マーカーの手前で方向を変え、次のマーカーへ\n4. この動作を繰り返してゴールまで進みます\n5. 逆方向からも同様に実施\n\n【方向転換のコツ】\n• 膝を軽く曲げて重心を低く保つ\n• 外側の足で踏ん張って方向転換\n• 上体をターンする方向に傾ける\n• 膝が内側に入らないよう注意\n\n【進歩段階】\n• 歩行 → 早歩き → ジョギング\n• マーカー間隔を短くして難易度アップ',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 4,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 2,
      precautions: JSON.stringify(['急激な方向転換を避ける', '膝の安定性を確認', '転倒防止']),
      contraindications: JSON.stringify(['膝の不安定性がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'ラダートレーニング（基礎）',
      description: '敏捷性と足のコーディネーションを向上させる練習',
      instructions: '【準備】\n• アジリティラダー（または床にテープでマス目を作成）\n• 各マスは約40cm四方\n• 5-8マス程度の長さ\n\n【基本パターン1: インアウト】\n1. ラダーの端に立ちます\n2. 右足→左足の順で最初のマスに入ります\n3. 右足→左足の順でマスの外（右側）に出ます\n4. 再び右足→左足でマスに入り、左側に出ます\n5. この動作を最後まで繰り返します\n\n【基本パターン2: 両足ジャンプ】\n1. 両足を揃えて最初のマスにジャンプイン\n2. 両足で次のマスにジャンプ\n3. リズムよく最後まで進みます\n\n【注意点】\n• 最初はゆっくり正確に\n• 膝を軽く曲げてバランスを保つ\n• リズムを意識する',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 3,
      default_duration_seconds: 0,
      rest_time_seconds: 60,
      order_index: 3,
      precautions: JSON.stringify(['正確性を重視', 'スピードより安全性', '転倒に注意']),
      contraindications: JSON.stringify(['足首に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'Tテスト（修正版）',
      description: '前後左右の動きを組み合わせた総合的なアジリティテスト',
      instructions: '【準備】\n• T字型にコーンを4個配置\n• 前後の距離：5メートル\n• 左右の距離：各2.5メートル\n\n【実施方法】\n1. 中央のコーン（Tの下部）からスタート\n2. 前方のコーンまで走ります（またはハイキングペース）\n3. 右のコーンまで横移動（サイドステップ）\n4. 左のコーンまで横移動\n5. 中央のコーンに戻り、スタート地点まで後退\n\n【動作のポイント】\n• 前進時：正面を向いて走る\n• 横移動時：体を横向きにしてサイドステップ\n• 後退時：小刻みなバックステップ\n• 各コーンでは手でタッチ\n\n【安全配慮】\n• 最初は歩行ペースから開始\n• 慣れてきたら徐々にスピードアップ\n• 正確性を重視',
      difficulty_level: 'advanced',
      default_sets: 2,
      default_reps: 3,
      default_duration_seconds: 0,
      rest_time_seconds: 120,
      order_index: 4,
      precautions: JSON.stringify(['十分なウォーミングアップ', '正確なフォーム', '無理なスピードアップは避ける']),
      contraindications: JSON.stringify(['膝の不安定性がある場合', '心肺機能に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 競技復帰期 - 競技特異的訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'カッティング動作（基礎）',
      description: '競技復帰に向けた安全な方向転換動作の習得',
      instructions: '【準備】\n• 10メートルの直線コースを設定\n• 5メートル地点にマーカーを設置\n• 適切なスポーツシューズを着用\n• 十分なウォームアップを実施\n\n【実施方法】\n1. スタート地点から軽いジョギングで前進\n2. マーカー地点で以下の手順で方向転換：\n   - 速度を少し落とす\n   - 外側の足（右にカットなら左足）でしっかり踏ん張る\n   - 膝を軽く曲げて重心を下げる\n   - 上体をターンする方向に傾ける\n   - 膝が内側に入らないよう注意\n3. 新しい方向に3-4歩加速\n4. 左右両方向で実施\n\n【段階的進歩】\n• レベル1: 歩行ペースでのカット\n• レベル2: ジョギングペースでのカット\n• レベル3: 競技に近いスピードでのカット\n\n【チェックポイント】\n• 膝とつま先の向きが揃っている\n• バランスを保って着地している\n• スムーズな方向転換ができている',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 1,
      precautions: JSON.stringify(['十分なウォームアップ必須', '適切なカッティングフォーム', '膝の安定性確認', '段階的なスピードアップ']),
      contraindications: JSON.stringify(['医師の競技復帰許可がない場合', '膝の不安定性がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'スプリント（段階的）',
      description: '競技復帰に向けた段階的な走行練習',
      instructions: '【準備】\n• 20-30メートルの直線コースを確保\n• 適切なランニングシューズを着用\n• 十分なウォームアップを実施\n\n【段階1: 軽いジョギング（週1-2）】\n1. 60-70%程度の軽い強度で走行\n2. 距離：20メートル × 5本\n3. 各本の間は歩いて完全回復\n\n【段階2: 中強度走行（週3-4）】\n1. 80%程度の強度で走行\n2. 距離：30メートル × 4本\n3. 休息時間：各本の間90秒\n\n【段階3: 高強度スプリント（週5以降）】\n1. 90-95%の強度で走行\n2. 距離：30メートル × 3本\n3. 休息時間：各本の間2-3分\n\n【フォームチェック】\n• 膝の向きが正面を向いている\n• 着地時の膝の安定性\n• 左右対称な走行パターン\n• 痛みや違和感がない',
      difficulty_level: 'advanced',
      default_sets: 1,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 2,
      precautions: JSON.stringify(['段階的な強度上昇', '痛みが出たら中止', '十分な休息', 'フォームの確認']),
      contraindications: JSON.stringify(['心肺機能に問題がある場合', '下肢に痛みがある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'ジャンプ&ランディング（上級）',
      description: '競技復帰に向けた高度なジャンプと着地の練習',
      instructions: '【準備】\n• 十分なスペースの確保\n• 適切なシューズの着用\n• ウォームアップの完了\n\n【エクササイズ1: リアクティブジャンプ】\n1. コーチや仲間の合図でジャンプ\n2. 様々な方向（前後左右）にジャンプ\n3. 予期しない方向への対応能力を向上\n4. 各セット：8-10回のジャンプ\n\n【エクササイズ2: デプスジャンプ】\n1. 30-40cmの台から飛び降り\n2. 着地と同時に垂直ジャンプ\n3. 着地時の衝撃吸収とリアクション力を向上\n4. 各セット：5-6回\n\n【エクササイズ3: マルチディレクション着地】\n1. 前方、後方、左右への連続ジャンプ\n2. 各方向での正確な着地を意識\n3. 方向転換時の膝の安定性を強化\n\n【着地時のチェックポイント】\n• 膝とつま先の向きが揃っている\n• 膝が内側に入らない（Knee-in回避）\n• 静音着地（着地音が小さい）\n• バランスの保持（3秒間静止）',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 3,
      rest_time_seconds: 120,
      order_index: 3,
      precautions: JSON.stringify(['十分な筋力獲得後に実施', '正確な着地フォーム', '疲労時は中止', '段階的な負荷増加']),
      contraindications: JSON.stringify(['膝の不安定性がある場合', '下肢筋力が不十分な場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'スポーツ特異的動作練習',
      description: '各競技に特化した動作パターンの練習',
      instructions: '【サッカー・フットサル】\n• ボールを使ったドリブル練習\n• シュート動作（膝の安定性重視）\n• ヘディング時の着地練習\n\n【バスケットボール】\n• ドリブル中の急停止練習\n• ジャンプシュート動作\n• ディフェンス時の横移動\n\n【バレーボール】\n• スパイク時のジャンプと着地\n• レシーブ時の低い姿勢維持\n• ブロック時の着地動作\n\n【テニス・バドミントン】\n• 前後左右への素早い移動\n• ストップ＆ゴー動作\n• 回転動作（フォアハンド、バックハンド）\n\n【ランニング・陸上】\n• カーブ走行練習\n• ハードル動作（模擬）\n• スタートダッシュ練習\n\n【共通の注意点】\n• 競技復帰は医師の許可後\n• 段階的な負荷増加\n• 痛みや違和感があれば中止\n• 正しいフォームの維持\n• 十分な休息の確保',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 0,
      rest_time_seconds: 120,
      order_index: 4,
      precautions: JSON.stringify(['医師の競技復帰許可必須', '段階的な練習強度', '正確なフォーム', '痛みモニタリング']),
      contraindications: JSON.stringify(['競技復帰許可がない場合', '基礎体力が不十分な場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 競技復帰期 - 外傷予防訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'FIFA 11+プログラム',
      description: 'FIFA推奨の外傷予防プログラム（サッカー向け）',
      instructions: '【第1部: ランニング・エクササイズ（8分）】\n1. まっすぐ走る（2分）\n2. ヒップアウト走（膝を外に）\n3. ヒップイン走（膝を内に）\n4. サークル・パートナー走\n5. ジャンプ・ヘディング\n6. ショルダー・コンタクト走\n\n【第2部: 筋力・プライオ・バランス（10分）】\n1. ザ・ベンチ（体幹・太もも強化）\n2. サイドワイズ・ベンチ（体幹側面）\n3. ハムストリングス\n4. シングル・レッグ・スタンス\n5. スクワット\n6. ジャンピング\n\n【第3部: ランニング・エクササイズ（2分）】\n1. アクロス・ザ・ピッチ\n2. バウンディング\n3. プラント・アンド・カット\n\n【実施のポイント】\n• 週2-3回の頻度で実施\n• 練習前のウォームアップとして\n• 正確なフォームを重視\n• 段階的な強度増加',
      difficulty_level: 'advanced',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 1200, // 20分
      rest_time_seconds: 0,
      order_index: 1,
      precautions: JSON.stringify(['段階的な負荷増加', '正しいフォームの維持', '適切なウォームアップ']),
      contraindications: JSON.stringify(['急性期の症状がある場合', '下肢に痛みがある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'PEP（Prevent injury and Enhance Performance）',
      description: '女子アスリート向けACL損傷予防プログラム',
      instructions: '【ウォームアップ（5分）】\n• 軽いジョギング\n• サイドシャッフル\n• バックペダル\n• カリオカステップ\n\n【ストレッチング（3分）】\n• カーフストレッチ\n• クアドストレッチ\n• フィギュア4ストレッチ\n• ヒップフレクサーストレッチ\n\n【強化エクササイズ（15分）】\n1. ウォーキング・ランジ（各方向）\n2. ロシアン・ハムストリング\n3. シングル・トー・レイズ\n4. スクワット・ジャンプ\n5. バウンディング・イン・プレイス\n6. 180度ターン\n7. ブロッキング\n\n【クールダウン（2分）】\n• 軽いジョギング\n• 静的ストレッチ\n\n【実施頻度】\n• 週3回、練習前に実施\n• シーズンを通して継続\n• 各エクササイズは正確なフォームで実施',
      difficulty_level: 'advanced',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 1500, // 25分
      rest_time_seconds: 0,
      order_index: 2,
      precautions: JSON.stringify(['女性アスリートに特に推奨', '正確なフォーム', '継続的な実施']),
      contraindications: JSON.stringify(['急性損傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'ニューロマスキュラートレーニング',
      description: '神経筋協調性を向上させる予防訓練',
      instructions: '【バランス・安定性訓練（10分）】\n1. 片足立ち（目を開けて/閉じて）\n2. 不安定面での片足立ち\n3. ダイナミック・バランス\n4. ボールキャッチ・バランス\n\n【プライオメトリック訓練（10分）】\n1. 両足ホッピング\n2. 片足ホッピング\n3. 前後ジャンプ\n4. 左右ジャンプ\n5. 対角ジャンプ\n\n【リアクション訓練（8分）】\n1. ミラー・エクササイズ\n2. 方向変換ドリル\n3. 急停止練習\n4. 予期しない方向への反応\n\n【機能的動作パターン（12分）】\n1. ファンクショナル・スクワット\n2. ランジ・パターン\n3. ステップ・アップ・ダウン\n4. カッティング・ムーブメント\n\n【効果】\n• 膝関節の安定性向上\n• 神経筋反応時間の短縮\n• 動的バランス能力の向上\n• 外傷リスクの軽減',
      difficulty_level: 'intermediate',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 2400, // 40分
      rest_time_seconds: 0,
      order_index: 3,
      precautions: JSON.stringify(['段階的な難易度上昇', '疲労時は中止', '正確な動作パターン']),
      contraindications: JSON.stringify(['急性症状がある場合', '平衡感覚に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'セカンダリー・インジュリー予防',
      description: 'ACL再建術後の再受傷防止のための特別プログラム',
      instructions: '【日常チェック項目】\n• 朝の膝の状態確認\n• 痛みや腫れの有無\n• 可動域の確認\n• 筋力バランスの自己評価\n\n【練習前の必須チェック】\n1. 十分なウォームアップ（15分以上）\n2. 膝の安定性テスト\n3. 患側と健側の筋力差確認\n4. バランス能力の確認\n\n【練習中の注意点】\n• 疲労を感じたら無理をしない\n• 違和感があればすぐに中止\n• 水分補給の徹底\n• 適切な休息の確保\n\n【練習後のケア】\n1. クールダウン（10分以上）\n2. アイシング（必要に応じて）\n3. ストレッチング\n4. 膝の状態記録\n\n【長期管理】\n• 定期的な医師診察\n• フィジオセラピストとの連携\n• 筋力測定（3ヶ月毎）\n• MRI検査（医師判断）\n\n【再受傷の危険信号】\n• 膝の不安定感\n• 原因不明の痛み\n• 腫れの増大\n• 可動域の制限\n• パフォーマンスの低下',
      difficulty_level: 'beginner',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 0,
      rest_time_seconds: 0,
      order_index: 4,
      precautions: JSON.stringify(['継続的なモニタリング', '医療チームとの連携', '早期発見・早期対応']),
      contraindications: JSON.stringify(['無症状でも油断は禁物']),
      requires_ai_analysis: false,
      is_active: true,
    },
  ]);
};