exports.seed = async function(knex) {
  // Delete all existing entries
  await knex('exercises').del();
  
  // Get category IDs
  const categories = await knex('exercise_categories').select('id', 'name', 'phase');
  
  const getCategory = (name) => categories.find(cat => cat.name === name);

  // Insert seed entries
  await knex('exercises').insert([
    // 術前期 - 基本動作訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基本動作訓練')?.id,
      name: '立ち上がり練習',
      description: '椅子からの立ち上がり動作の練習',
      instructions: '1. 椅子に深く座る\n2. 両手を胸の前で組む\n3. 前傾しながらゆっくり立ち上がる\n4. 膝に痛みがない範囲で行う',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 0,
      rest_time_seconds: 30,
      order_index: 1,
      precautions: JSON.stringify(['膝に痛みを感じた場合は中止', '転倒に注意']),
      contraindications: JSON.stringify(['急性期の強い痛み', '腫脹が著明な場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基本動作訓練')?.id,
      name: '階段昇降練習',
      description: '手すりを使った階段の昇り降り練習',
      instructions: '1. 手すりをしっかり握る\n2. 健側足から上る\n3. 患側足から降りる\n4. 無理をせず一段ずつ',
      difficulty_level: 'intermediate',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 60,
      order_index: 2,
      precautions: JSON.stringify(['必ず手すりを使用', '転倒防止に細心の注意']),
      contraindications: JSON.stringify(['バランス感覚に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 術前期 - 筋力維持
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: '大腿四頭筋セッティング',
      description: '膝を伸ばした状態で太ももの前の筋肉を収縮させる基本的な筋力訓練',
      instructions: '【開始姿勢】\n• 仰向けに寝るか、長座位（足を伸ばして座る）\n• 膝の下にタオルを置いても可\n\n【実施方法】\n1. 膝をピンと真っ直ぐに伸ばします\n2. 太ももの前の筋肉（大腿四頭筋）にぐっと力を入れます\n3. 膝裏でタオルや床を押すイメージで5秒間キープ\n4. 力を抜いてリラックス\n\n【コツ】\n• 太ももの前が硬くなるのを手で触って確認\n• 膝のお皿が上に持ち上がる感覚\n• 呼吸は止めずに自然に',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 15,
      default_duration_seconds: 5,
      rest_time_seconds: 10,
      order_index: 1,
      precautions: JSON.stringify(['痛みの範囲内で実施', '強い痛みがある時は中止']),
      contraindications: JSON.stringify(['急性炎症期', '医師から安静指示がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: 'ハムストリングス強化',
      description: '太ももの裏側の筋肉を強化する運動',
      instructions: '【開始姿勢】\n• うつ伏せに寝ます\n• 枕を腰の下に入れても可\n\n【実施方法】\n1. 片足のかかとをお尻に向けてゆっくり曲げます\n2. 太ももの裏側に力が入るのを感じながら3秒キープ\n3. ゆっくりと元の位置に戻します\n4. 反対の足も同様に行います\n\n【コツ】\n• 腰を反らさないよう注意\n• 太ももは床から浮かせない\n• 膝を曲げる時は勢いをつけずゆっくりと',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 12,
      default_duration_seconds: 3,
      rest_time_seconds: 15,
      order_index: 2,
      precautions: JSON.stringify(['腰痛に注意', '無理な力は入れない']),
      contraindications: JSON.stringify(['腰椎に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: '足首の運動',
      description: '足首を動かして血流を改善し、下肢の筋力維持を図る',
      instructions: '【開始姿勢】\n• 仰向けまたは座った状態\n• 足は楽にしておきます\n\n【実施方法】\n1. つま先を天井に向けて反らします（背屈）\n2. 3秒キープしてから足首を下に向けます（底屈）\n3. 次に足首を時計回りに大きく回します\n4. 反時計回りにも回します\n\n【バリエーション】\n• 文字を書くように足首を動かす\n• 両足同時に行う\n• 片足ずつ丁寧に行う',
      difficulty_level: 'beginner',
      default_sets: 2,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 5,
      order_index: 3,
      precautions: JSON.stringify(['痛みがあれば中止', '無理に大きく動かさない']),
      contraindications: JSON.stringify(['足首に外傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 術直後期 - 可動域改善
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: 'ヒールスライド',
      description: 'かかとを滑らせながら膝の屈曲練習を行い、徐々に可動域を回復させる',
      instructions: '【開始姿勢】\n• 仰向けに寝ます\n• 両足を伸ばした状態\n• タオルをかかとの下に敷くと滑りやすい\n\n【実施方法】\n1. 患側（手術した側）の足のかかとを床につけたまま滑らせます\n2. ゆっくりと膝を曲げていきます\n3. 痛みのない範囲で最大まで曲げます\n4. 3秒間その位置を保持\n5. ゆっくりと元の位置に戻します\n\n【注意点】\n• 無理に曲げようとしない\n• 毎日少しずつ曲がる角度を増やす\n• 痛みが増す場合は範囲を狭める',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 1,
      precautions: JSON.stringify(['痛みが強い場合は中止', '無理に曲げない', '腫れが増した場合は休む']),
      contraindications: JSON.stringify(['医師の許可がない場合', '感染の兆候がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: '膝伸展運動（座位）',
      description: '椅子に座った状態で膝を伸ばす練習',
      instructions: '【開始姿勢】\n• 椅子に深く座ります\n• 背もたれに背中をつける\n• 足裏は床につけて90度に曲げた状態\n\n【実施方法】\n1. 患側の膝をゆっくりと伸ばしていきます\n2. 可能な限り真っ直ぐになるまで伸ばします\n3. 3秒間その位置でキープ\n4. ゆっくりと元の90度の位置に戻します\n\n【進歩の目安】\n• 完全に伸びるようになることが目標\n• 左右差がなくなることを確認',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 12,
      default_duration_seconds: 3,
      rest_time_seconds: 20,
      order_index: 2,
      precautions: JSON.stringify(['膝の後ろが突っ張る程度の痛みは正常', '鋭い痛みは中止']),
      contraindications: JSON.stringify(['膝に熱感がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: '膝蓋骨モビライゼーション',
      description: '膝のお皿を動かして関節の動きを良くする',
      instructions: '【開始姿勢】\n• 仰向けまたは長座位\n• 膝を伸ばした状態\n\n【実施方法】\n1. 膝のお皿（膝蓋骨）を両手の親指と人差し指で軽くつまみます\n2. 上下左右に優しく動かします\n3. 各方向に5秒ずつ軽く押します\n4. 円を描くように優しく動かします\n\n【注意】\n• 強く押しすぎない\n• 膝蓋骨の周りがほぐれる感覚\n• 痛みがあれば力を弱める',
      difficulty_level: 'beginner',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 5,
      rest_time_seconds: 10,
      order_index: 3,
      precautions: JSON.stringify(['優しく行う', '強い圧迫は避ける']),
      contraindications: JSON.stringify(['膝蓋骨に外傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 基礎回復期 - 歩行訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '正常歩行練習',
      description: '正しい歩き方を意識して歩行パターンを改善する',
      instructions: '【準備】\n• 平らで滑らない場所で実施\n• 10-20メートルの歩行距離を確保\n• 必要に応じて杖や手すりを使用\n\n【実施方法】\n1. まず正しい立位姿勢を作ります\n2. 健側足から歩き始めます\n3. かかとから着地し、つま先で蹴り出します\n4. 歩幅は左右同じになるよう意識\n5. 膝は真っ直ぐ前に向けて歩きます\n\n【チェックポイント】\n• 上体がまっすぐ\n• 腕の振りが自然\n• 足音が左右同じ',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 1,
      default_duration_seconds: 60,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['転倒防止', '疲労に注意', '痛みがあれば休憩']),
      contraindications: JSON.stringify(['荷重制限がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '片脚立位',
      description: '患側での片脚立位練習でバランス能力を向上させる',
      instructions: '【準備】\n• 安全な場所で実施\n• 壁や手すりの近くに立つ\n• 必要に応じて支えを使用\n\n【実施方法】\n1. 両足で安定して立ちます\n2. 健側足をゆっくり床から離します\n3. 患側足一本でバランスを取ります\n4. 目標時間まで維持します\n5. 慣れてきたら目を閉じて挑戦\n\n【段階的進歩】\n• 最初は5秒から開始\n• 徐々に30秒まで延長\n• 手の支えなしで実施',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 5,
      default_duration_seconds: 10,
      rest_time_seconds: 30,
      order_index: 2,
      precautions: JSON.stringify(['転倒防止', '支持物の準備', '無理をしない']),
      contraindications: JSON.stringify(['著明な不安定性', '平衡感覚障害']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '階段昇降（基礎）',
      description: '手すりを使用した安全な階段昇降の練習',
      instructions: '【準備】\n• 手すりがある階段で実施\n• 滑り止めのある靴を着用\n• 介助者がいると安心\n\n【昇る時の方法】\n1. 健側足を先に一段上に置きます\n2. 手すりを握りながら体重を移します\n3. 患側足を同じ段に置きます\n4. 一段ずつ確実に昇ります\n\n【降りる時の方法】\n1. 患側足を先に一段下に置きます\n2. 手すりでしっかり支えながら\n3. 健側足を同じ段に置きます\n\n【覚え方】\n昇りは「良い足から」、降りは「悪い足から」',
      difficulty_level: 'intermediate',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 3,
      precautions: JSON.stringify(['必ず手すりを使用', '転倒防止', '一段ずつ確実に']),
      contraindications: JSON.stringify(['バランス感覚に問題がある場合', '膝の痛みが強い場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 筋力強化期 - 筋力強化
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'ウォールスクワット',
      description: '壁に背中をつけて行う安全なスクワット運動',
      instructions: '【開始姿勢】\n• 壁に背中をつけて立ちます\n• 足は肩幅程度に開き、壁から30cm程前に\n• 両手は腰に当てるか胸の前で組む\n\n【実施方法】\n1. 壁に背中を滑らせながらゆっくり膝を曲げます\n2. 膝が90度になるまで（椅子に座る程度）\n3. 太ももと床が平行になったら3秒キープ\n4. 壁を押しながらゆっくり立ち上がります\n\n【コツ】\n• 膝がつま先より前に出ないよう注意\n• 重心はかかと寄りに\n• 呼吸を止めずに実施',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 3,
      rest_time_seconds: 45,
      order_index: 1,
      precautions: JSON.stringify(['膝の位置に注意', '痛みのない範囲で実施']),
      contraindications: JSON.stringify(['腰痛がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'ミニスクワット',
      description: '膝屈曲30度までの浅いスクワットで安全に筋力強化',
      instructions: '【開始姿勢】\n• 足を肩幅に開いて立ちます\n• つま先は軽く外向きに\n• 手は腰に当てるか前に伸ばす\n\n【実施方法】\n1. ゆっくりと膝を曲げ始めます\n2. 膝の角度が30度程度（浅く座る程度）まで曲げます\n3. その位置で3秒間キープ\n4. ゆっくりと元の立位に戻します\n\n【注意点】\n• 深く曲げすぎない\n• 膝とつま先の向きを揃える\n• 上体は軽く前傾させる',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 45,
      order_index: 2,
      precautions: JSON.stringify(['膝がつま先より前に出ない', '痛みのない範囲', '浅い角度から開始']),
      contraindications: JSON.stringify(['膝蓋大腿関節症状が強い場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'レッグプレス（自重）',
      description: '仰向けで行う下肢筋力強化運動',
      instructions: '【開始姿勢】\n• 仰向けに寝ます\n• 膝を90度に曲げて足裏を床につける\n• 両手は体の横に置く\n\n【実施方法】\n1. 片足を床から離し膝を胸に近づけます\n2. その足をゆっくりと伸ばしていきます\n3. 床につく手前で止めて3秒キープ\n4. ゆっくりと膝を曲げて元の位置に\n5. 反対の足も同様に実施\n\n【段階的進歩】\n• 最初は膝を完全に伸ばさなくても良い\n• 慣れてきたら足首に重りをつけて負荷を追加',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 3,
      precautions: JSON.stringify(['腰を反らさない', '膝に痛みがあれば中止']),
      contraindications: JSON.stringify(['腰痛がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 筋力強化期 - バランス訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('バランス訓練')?.id,
      name: 'バランスボード',
      description: 'バランスボードを使った安定性訓練',
      instructions: '1. バランスボードの上に立つ\n2. 両足で体重を支える\n3. バランスを保つ\n4. 慣れてきたら片足で実施',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 1,
      default_duration_seconds: 30,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['転倒防止対策', '段階的に難易度アップ']),
      contraindications: JSON.stringify(['重度のバランス障害']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 機能訓練期 - スポーツ動作訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: 'ジャンプ着地',
      description: '両足でのジャンプ着地練習',
      instructions: '1. 両足で軽くジャンプ\n2. 膝を軽く曲げて着地\n3. バランスを保つ\n4. 着地音を小さく',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 0,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['適切な着地フォーム', 'Knee in Toe out注意']),
      contraindications: JSON.stringify(['膝の不安定性が残存']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 機能訓練期 - アジリティ訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'ラテラルステップ',
      description: '横方向への素早いステップ動作',
      instructions: '1. 足を肩幅に開く\n2. 横方向に素早くステップ\n3. 膝の向きに注意\n4. 反対側も同様に実施',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 0,
      rest_time_seconds: 45,
      order_index: 1,
      precautions: JSON.stringify(['膝の内反動作を避ける', '適切なフォーム維持']),
      contraindications: JSON.stringify(['競技復帰許可が出ていない場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 競技復帰期 - 競技特異的訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'カッティング動作',
      description: '方向転換動作の練習',
      instructions: '1. 前方に走る\n2. マーカーで方向転換\n3. 膝の位置に注意\n4. 段階的にスピードアップ',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 1,
      precautions: JSON.stringify(['十分なウォームアップ', '適切なカッティングフォーム']),
      contraindications: JSON.stringify(['医師の競技復帰許可がない場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 競技復帰期 - 外傷予防訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'FIFA 11+準備運動',
      description: 'FIFA推奨の外傷予防プログラム',
      instructions: '1. 動的ストレッチ\n2. 筋力強化運動\n3. プライオメトリクス\n4. アジリティ運動',
      difficulty_level: 'advanced',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 900, // 15分
      rest_time_seconds: 0,
      order_index: 1,
      precautions: JSON.stringify(['段階的な負荷増加', '正しいフォームの維持']),
      contraindications: JSON.stringify(['急性期の症状がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
  ]);
};