exports.seed = async function(knex) {
  // Delete all existing entries
  await knex('exercises').del();
  
  // Get category IDs
  const categories = await knex('exercise_categories').select('id', 'name', 'phase');
  
  const getCategory = (name) => categories.find(cat => cat.name === name);

  // Insert seed entries
  await knex('exercises').insert([
    // 術前期 - 基本動作訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基本動作訓練')?.id,
      name: '立ち上がり練習',
      description: '椅子からの立ち上がり動作の練習',
      instructions: '1. 椅子に深く座る\n2. 両手を胸の前で組む\n3. 前傾しながらゆっくり立ち上がる\n4. 膝に痛みがない範囲で行う',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 0,
      rest_time_seconds: 30,
      order_index: 1,
      precautions: JSON.stringify(['膝に痛みを感じた場合は中止', '転倒に注意']),
      contraindications: JSON.stringify(['急性期の強い痛み', '腫脹が著明な場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('基本動作訓練')?.id,
      name: '階段昇降練習',
      description: '手すりを使った階段の昇り降り練習',
      instructions: '1. 手すりをしっかり握る\n2. 健側足から上る\n3. 患側足から降りる\n4. 無理をせず一段ずつ',
      difficulty_level: 'intermediate',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 60,
      order_index: 2,
      precautions: JSON.stringify(['必ず手すりを使用', '転倒防止に細心の注意']),
      contraindications: JSON.stringify(['バランス感覚に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 術前期 - 筋力維持
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: '大腿四頭筋セッティング',
      description: '膝を伸ばした状態で太ももの前の筋肉を収縮させる基本的な筋力訓練',
      instructions: '【開始姿勢】\n• 仰向けに寝るか、長座位（足を伸ばして座る）\n• 膝の下にタオルを置いても可\n\n【実施方法】\n1. 膝をピンと真っ直ぐに伸ばします\n2. 太ももの前の筋肉（大腿四頭筋）にぐっと力を入れます\n3. 膝裏でタオルや床を押すイメージで5秒間キープ\n4. 力を抜いてリラックス\n\n【コツ】\n• 太ももの前が硬くなるのを手で触って確認\n• 膝のお皿が上に持ち上がる感覚\n• 呼吸は止めずに自然に',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 15,
      default_duration_seconds: 5,
      rest_time_seconds: 10,
      order_index: 1,
      precautions: JSON.stringify(['痛みの範囲内で実施', '強い痛みがある時は中止']),
      contraindications: JSON.stringify(['急性炎症期', '医師から安静指示がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: 'ハムストリングス強化',
      description: '太ももの裏側の筋肉を強化する運動',
      instructions: '【開始姿勢】\n• うつ伏せに寝ます\n• 枕を腰の下に入れても可\n\n【実施方法】\n1. 片足のかかとをお尻に向けてゆっくり曲げます\n2. 太ももの裏側に力が入るのを感じながら3秒キープ\n3. ゆっくりと元の位置に戻します\n4. 反対の足も同様に行います\n\n【コツ】\n• 腰を反らさないよう注意\n• 太ももは床から浮かせない\n• 膝を曲げる時は勢いをつけずゆっくりと',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 12,
      default_duration_seconds: 3,
      rest_time_seconds: 15,
      order_index: 2,
      precautions: JSON.stringify(['腰痛に注意', '無理な力は入れない']),
      contraindications: JSON.stringify(['腰椎に問題がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力維持')?.id,
      name: '足首の運動',
      description: '足首を動かして血流を改善し、下肢の筋力維持を図る',
      instructions: '【開始姿勢】\n• 仰向けまたは座った状態\n• 足は楽にしておきます\n\n【実施方法】\n1. つま先を天井に向けて反らします（背屈）\n2. 3秒キープしてから足首を下に向けます（底屈）\n3. 次に足首を時計回りに大きく回します\n4. 反時計回りにも回します\n\n【バリエーション】\n• 文字を書くように足首を動かす\n• 両足同時に行う\n• 片足ずつ丁寧に行う',
      difficulty_level: 'beginner',
      default_sets: 2,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 5,
      order_index: 3,
      precautions: JSON.stringify(['痛みがあれば中止', '無理に大きく動かさない']),
      contraindications: JSON.stringify(['足首に外傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 術直後期 - 可動域改善
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: 'ヒールスライド',
      description: 'かかとを滑らせながら膝の屈曲練習を行い、徐々に可動域を回復させる',
      instructions: '【開始姿勢】\n• 仰向けに寝ます\n• 両足を伸ばした状態\n• タオルをかかとの下に敷くと滑りやすい\n\n【実施方法】\n1. 患側（手術した側）の足のかかとを床につけたまま滑らせます\n2. ゆっくりと膝を曲げていきます\n3. 痛みのない範囲で最大まで曲げます\n4. 3秒間その位置を保持\n5. ゆっくりと元の位置に戻します\n\n【注意点】\n• 無理に曲げようとしない\n• 毎日少しずつ曲がる角度を増やす\n• 痛みが増す場合は範囲を狭める',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 1,
      precautions: JSON.stringify(['痛みが強い場合は中止', '無理に曲げない', '腫れが増した場合は休む']),
      contraindications: JSON.stringify(['医師の許可がない場合', '感染の兆候がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: '膝伸展運動（座位）',
      description: '椅子に座った状態で膝を伸ばす練習',
      instructions: '【開始姿勢】\n• 椅子に深く座ります\n• 背もたれに背中をつける\n• 足裏は床につけて90度に曲げた状態\n\n【実施方法】\n1. 患側の膝をゆっくりと伸ばしていきます\n2. 可能な限り真っ直ぐになるまで伸ばします\n3. 3秒間その位置でキープ\n4. ゆっくりと元の90度の位置に戻します\n\n【進歩の目安】\n• 完全に伸びるようになることが目標\n• 左右差がなくなることを確認',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 12,
      default_duration_seconds: 3,
      rest_time_seconds: 20,
      order_index: 2,
      precautions: JSON.stringify(['膝の後ろが突っ張る程度の痛みは正常', '鋭い痛みは中止']),
      contraindications: JSON.stringify(['膝に熱感がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('可動域改善')?.id,
      name: '膝蓋骨モビライゼーション',
      description: '膝のお皿を動かして関節の動きを良くする',
      instructions: '【開始姿勢】\n• 仰向けまたは長座位\n• 膝を伸ばした状態\n\n【実施方法】\n1. 膝のお皿（膝蓋骨）を両手の親指と人差し指で軽くつまみます\n2. 上下左右に優しく動かします\n3. 各方向に5秒ずつ軽く押します\n4. 円を描くように優しく動かします\n\n【注意】\n• 強く押しすぎない\n• 膝蓋骨の周りがほぐれる感覚\n• 痛みがあれば力を弱める',
      difficulty_level: 'beginner',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 5,
      rest_time_seconds: 10,
      order_index: 3,
      precautions: JSON.stringify(['優しく行う', '強い圧迫は避ける']),
      contraindications: JSON.stringify(['膝蓋骨に外傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 基礎回復期 - 歩行訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '正常歩行練習',
      description: '正しい歩き方を意識して歩行パターンを改善する',
      instructions: '【準備】\n• 平らで滑らない場所で実施\n• 10-20メートルの歩行距離を確保\n• 必要に応じて杖や手すりを使用\n\n【実施方法】\n1. まず正しい立位姿勢を作ります\n2. 健側足から歩き始めます\n3. かかとから着地し、つま先で蹴り出します\n4. 歩幅は左右同じになるよう意識\n5. 膝は真っ直ぐ前に向けて歩きます\n\n【チェックポイント】\n• 上体がまっすぐ\n• 腕の振りが自然\n• 足音が左右同じ',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 1,
      default_duration_seconds: 60,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['転倒防止', '疲労に注意', '痛みがあれば休憩']),
      contraindications: JSON.stringify(['荷重制限がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '片脚立位',
      description: '患側での片脚立位練習でバランス能力を向上させる',
      instructions: '【準備】\n• 安全な場所で実施\n• 壁や手すりの近くに立つ\n• 必要に応じて支えを使用\n\n【実施方法】\n1. 両足で安定して立ちます\n2. 健側足をゆっくり床から離します\n3. 患側足一本でバランスを取ります\n4. 目標時間まで維持します\n5. 慣れてきたら目を閉じて挑戦\n\n【段階的進歩】\n• 最初は5秒から開始\n• 徐々に30秒まで延長\n• 手の支えなしで実施',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 5,
      default_duration_seconds: 10,
      rest_time_seconds: 30,
      order_index: 2,
      precautions: JSON.stringify(['転倒防止', '支持物の準備', '無理をしない']),
      contraindications: JSON.stringify(['著明な不安定性', '平衡感覚障害']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('歩行訓練')?.id,
      name: '階段昇降（基礎）',
      description: '手すりを使用した安全な階段昇降の練習',
      instructions: '【準備】\n• 手すりがある階段で実施\n• 滑り止めのある靴を着用\n• 介助者がいると安心\n\n【昇る時の方法】\n1. 健側足を先に一段上に置きます\n2. 手すりを握りながら体重を移します\n3. 患側足を同じ段に置きます\n4. 一段ずつ確実に昇ります\n\n【降りる時の方法】\n1. 患側足を先に一段下に置きます\n2. 手すりでしっかり支えながら\n3. 健側足を同じ段に置きます\n\n【覚え方】\n昇りは「良い足から」、降りは「悪い足から」',
      difficulty_level: 'intermediate',
      default_sets: 2,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 3,
      precautions: JSON.stringify(['必ず手すりを使用', '転倒防止', '一段ずつ確実に']),
      contraindications: JSON.stringify(['バランス感覚に問題がある場合', '膝の痛みが強い場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 筋力強化期 - 筋力強化
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'ウォールスクワット',
      description: '壁に背中をつけて行う安全なスクワット運動',
      instructions: '【開始姿勢】\n• 壁に背中をつけて立ちます\n• 足は肩幅程度に開き、壁から30cm程前に\n• 両手は腰に当てるか胸の前で組む\n\n【実施方法】\n1. 壁に背中を滑らせながらゆっくり膝を曲げます\n2. 膝が90度になるまで（椅子に座る程度）\n3. 太ももと床が平行になったら3秒キープ\n4. 壁を押しながらゆっくり立ち上がります\n\n【コツ】\n• 膝がつま先より前に出ないよう注意\n• 重心はかかと寄りに\n• 呼吸を止めずに実施',
      difficulty_level: 'beginner',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 3,
      rest_time_seconds: 45,
      order_index: 1,
      precautions: JSON.stringify(['膝の位置に注意', '痛みのない範囲で実施']),
      contraindications: JSON.stringify(['腰痛がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'ミニスクワット',
      description: '膝屈曲30度までの浅いスクワットで安全に筋力強化',
      instructions: '【開始姿勢】\n• 足を肩幅に開いて立ちます\n• つま先は軽く外向きに\n• 手は腰に当てるか前に伸ばす\n\n【実施方法】\n1. ゆっくりと膝を曲げ始めます\n2. 膝の角度が30度程度（浅く座る程度）まで曲げます\n3. その位置で3秒間キープ\n4. ゆっくりと元の立位に戻します\n\n【注意点】\n• 深く曲げすぎない\n• 膝とつま先の向きを揃える\n• 上体は軽く前傾させる',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 10,
      default_duration_seconds: 3,
      rest_time_seconds: 45,
      order_index: 2,
      precautions: JSON.stringify(['膝がつま先より前に出ない', '痛みのない範囲', '浅い角度から開始']),
      contraindications: JSON.stringify(['膝蓋大腿関節症状が強い場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('筋力強化')?.id,
      name: 'レッグプレス（自重）',
      description: '仰向けで行う下肢筋力強化運動',
      instructions: '【開始姿勢】\n• 仰向けに寝ます\n• 膝を90度に曲げて足裏を床につける\n• 両手は体の横に置く\n\n【実施方法】\n1. 片足を床から離し膝を胸に近づけます\n2. その足をゆっくりと伸ばしていきます\n3. 床につく手前で止めて3秒キープ\n4. ゆっくりと膝を曲げて元の位置に\n5. 反対の足も同様に実施\n\n【段階的進歩】\n• 最初は膝を完全に伸ばさなくても良い\n• 慣れてきたら足首に重りをつけて負荷を追加',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 3,
      rest_time_seconds: 30,
      order_index: 3,
      precautions: JSON.stringify(['腰を反らさない', '膝に痛みがあれば中止']),
      contraindications: JSON.stringify(['腰痛がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },

    // 筋力強化期 - バランス訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('バランス訓練')?.id,
      name: 'バランスボード',
      description: 'バランスボードを使った安定性訓練',
      instructions: '1. バランスボードの上に立つ\n2. 両足で体重を支える\n3. バランスを保つ\n4. 慣れてきたら片足で実施',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 1,
      default_duration_seconds: 30,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['転倒防止対策', '段階的に難易度アップ']),
      contraindications: JSON.stringify(['重度のバランス障害']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 機能訓練期 - スポーツ動作訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: '両足ジャンプ着地',
      description: '安全で正しい着地技術を習得するための基本的なジャンプ練習',
      instructions: '【準備】\n• 平らで滑らない床で実施\n• 運動靴を着用\n• 十分なスペースを確保\n\n【実施方法】\n1. 足を肩幅に開いて立ちます\n2. 軽く膝を曲げて、垂直に15-20cm程度ジャンプします\n3. 着地時は以下に注意：\n   - 足裏全体で着地\n   - 膝を軽く曲げてクッション性を保つ\n   - 膝とつま先の向きを揃える\n   - 上体はやや前傾\n4. 着地後2-3秒間バランスを保持\n\n【段階的進歩】\n• 最初は低いジャンプから開始\n• 慣れてきたら高さを上げる\n• 目を閉じて着地バランスに挑戦',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 3,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['適切な着地フォーム', '膝の内側への倒れ込み（Knee in）を避ける', '着地音を小さくする']),
      contraindications: JSON.stringify(['膝の不安定性が残存', '痛みがある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: '片足ジャンプ着地',
      description: '競技復帰に向けた高度な片足ジャンプと着地の練習',
      instructions: '【準備】\n• 両足ジャンプが安全にできることを確認\n• 安全な環境で実施\n\n【実施方法】\n1. 患側足で立ちます\n2. 軽く膝を曲げて前方に15cm程度ジャンプ\n3. 同じ足で着地します\n4. 着地のポイント：\n   - 膝を適度に曲げて衝撃を吸収\n   - 膝が内側に入らないよう注意\n   - 着地後3秒間バランス保持\n5. 健側足でも同様に実施\n\n【バリエーション】\n• 前後方向のジャンプ\n• 左右方向のジャンプ\n• 連続ジャンプ（2-3回）',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 5,
      default_duration_seconds: 3,
      rest_time_seconds: 90,
      order_index: 2,
      precautions: JSON.stringify(['十分な筋力がついてから実施', '膝の安定性を確認', '無理をしない']),
      contraindications: JSON.stringify(['膝の痛みや腫れがある場合', '筋力が不十分な場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: 'ボックスステップアップ',
      description: '段差を使った実用的な動作訓練',
      instructions: '【準備】\n• 高さ15-30cmの安定した台やステップを用意\n• 滑り止めのある靴を着用\n• 手すりや支えがあると安心\n\n【実施方法】\n1. 台の前に立ちます\n2. 患側足を台の上に置きます\n3. 体重を患側足に移しながら台に上がります\n4. 両足が台の上に揃ったら一旦停止\n5. ゆっくりと同じ順序で降ります\n\n【ポイント】\n• 膝がつま先より前に出ないよう注意\n• 上体を軽く前傾させて重心を安定\n• 勢いをつけずにコントロールして実施\n\n【段階的進歩】\n• 低い台から始めて徐々に高くする\n• 慣れてきたら手の支えなしで実施',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 0,
      rest_time_seconds: 45,
      order_index: 3,
      precautions: JSON.stringify(['台の安定性を確認', '転倒に注意', '膝の位置に注意']),
      contraindications: JSON.stringify(['バランス感覚に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('スポーツ動作訓練')?.id,
      name: 'フォワードランジ',
      description: '前方への大きな一歩と膝の安定性を強化する運動',
      instructions: '【開始姿勢】\n• 足を肩幅程度に開いて立ちます\n• 両手は腰に当てるか胸の前で組む\n\n【実施方法】\n1. 患側足を大きく前方に踏み出します（歩幅は約60-90cm）\n2. 前足に体重をかけながら膝を90度まで曲げます\n3. 後ろ足の膝は床に近づけますが触れません\n4. 前足で床を押して元の立位に戻ります\n5. 反対の足でも同様に実施\n\n【注意点】\n• 前に出した膝がつま先より前に出ない\n• 上体は真っ直ぐ保つ\n• バランスを崩さないよう慎重に\n\n【効果】\n• 太ももとお尻の筋力強化\n• 膝関節の安定性向上\n• バランス能力の向上',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 3,
      rest_time_seconds: 60,
      order_index: 4,
      precautions: JSON.stringify(['膝の位置に注意', 'バランスを崩さない', '深く曲げすぎない']),
      contraindications: JSON.stringify(['膝に痛みがある場合', '腰痛がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 機能訓練期 - アジリティ訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'ラテラルステップ（基礎）',
      description: '横方向への安全なステップ移動の練習',
      instructions: '【準備】\n• 3-4メートルの直線距離を確保\n• 床に目印となるマーカーやテープを置く\n• 滑りにくい靴を着用\n\n【実施方法】\n1. 足を肩幅に開いて立ちます\n2. 膝を軽く曲げた姿勢を保ちます\n3. 右方向に移動する場合：\n   - 右足を横に一歩踏み出します\n   - 左足を右足に近づけます\n   - 足が揃ったら再び右足を踏み出します\n4. 3-4歩移動したら左方向に同様に実施\n\n【ポイント】\n• 膝とつま先の向きを常に揃える\n• 上体は真っ直ぐ保つ\n• 最初はゆっくり、慣れてきたらスピードアップ\n\n【段階的進歩】\n• ゆっくりから中程度のスピードへ\n• 移動距離を徐々に延ばす',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 0,
      rest_time_seconds: 60,
      order_index: 1,
      precautions: JSON.stringify(['膝の内側への倒れ込みを避ける', '適切なフォーム維持', '転倒に注意']),
      contraindications: JSON.stringify(['膝の痛みがある場合', 'バランス感覚に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'ジグザグ歩行',
      description: '方向転換能力を向上させるジグザグパターンでの歩行練習',
      instructions: '【準備】\n• コーンやマーカーを5個、約2メートル間隔でジグザグに配置\n• 安全な靴を着用\n• 十分なスペースを確保\n\n【実施方法】\n1. スタート地点に立ちます\n2. 最初のマーカーに向かって歩きます\n3. マーカーの手前で方向を変え、次のマーカーへ\n4. この動作を繰り返してゴールまで進みます\n5. 逆方向からも同様に実施\n\n【方向転換のコツ】\n• 膝を軽く曲げて重心を低く保つ\n• 外側の足で踏ん張って方向転換\n• 上体をターンする方向に傾ける\n• 膝が内側に入らないよう注意\n\n【進歩段階】\n• 歩行 → 早歩き → ジョギング\n• マーカー間隔を短くして難易度アップ',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 4,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 2,
      precautions: JSON.stringify(['急激な方向転換を避ける', '膝の安定性を確認', '転倒防止']),
      contraindications: JSON.stringify(['膝の不安定性がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'ラダートレーニング（基礎）',
      description: '敏捷性と足のコーディネーションを向上させる練習',
      instructions: '【準備】\n• アジリティラダー（または床にテープでマス目を作成）\n• 各マスは約40cm四方\n• 5-8マス程度の長さ\n\n【基本パターン1: インアウト】\n1. ラダーの端に立ちます\n2. 右足→左足の順で最初のマスに入ります\n3. 右足→左足の順でマスの外（右側）に出ます\n4. 再び右足→左足でマスに入り、左側に出ます\n5. この動作を最後まで繰り返します\n\n【基本パターン2: 両足ジャンプ】\n1. 両足を揃えて最初のマスにジャンプイン\n2. 両足で次のマスにジャンプ\n3. リズムよく最後まで進みます\n\n【注意点】\n• 最初はゆっくり正確に\n• 膝を軽く曲げてバランスを保つ\n• リズムを意識する',
      difficulty_level: 'intermediate',
      default_sets: 3,
      default_reps: 3,
      default_duration_seconds: 0,
      rest_time_seconds: 60,
      order_index: 3,
      precautions: JSON.stringify(['正確性を重視', 'スピードより安全性', '転倒に注意']),
      contraindications: JSON.stringify(['足首に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('アジリティ訓練')?.id,
      name: 'Tテスト（修正版）',
      description: '前後左右の動きを組み合わせた総合的なアジリティテスト',
      instructions: '【準備】\n• T字型にコーンを4個配置\n• 前後の距離：5メートル\n• 左右の距離：各2.5メートル\n\n【実施方法】\n1. 中央のコーン（Tの下部）からスタート\n2. 前方のコーンまで走ります（またはハイキングペース）\n3. 右のコーンまで横移動（サイドステップ）\n4. 左のコーンまで横移動\n5. 中央のコーンに戻り、スタート地点まで後退\n\n【動作のポイント】\n• 前進時：正面を向いて走る\n• 横移動時：体を横向きにしてサイドステップ\n• 後退時：小刻みなバックステップ\n• 各コーンでは手でタッチ\n\n【安全配慮】\n• 最初は歩行ペースから開始\n• 慣れてきたら徐々にスピードアップ\n• 正確性を重視',
      difficulty_level: 'advanced',
      default_sets: 2,
      default_reps: 3,
      default_duration_seconds: 0,
      rest_time_seconds: 120,
      order_index: 4,
      precautions: JSON.stringify(['十分なウォーミングアップ', '正確なフォーム', '無理なスピードアップは避ける']),
      contraindications: JSON.stringify(['膝の不安定性がある場合', '心肺機能に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 競技復帰期 - 競技特異的訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'カッティング動作（基礎）',
      description: '競技復帰に向けた安全な方向転換動作の習得',
      instructions: '【準備】\n• 10メートルの直線コースを設定\n• 5メートル地点にマーカーを設置\n• 適切なスポーツシューズを着用\n• 十分なウォームアップを実施\n\n【実施方法】\n1. スタート地点から軽いジョギングで前進\n2. マーカー地点で以下の手順で方向転換：\n   - 速度を少し落とす\n   - 外側の足（右にカットなら左足）でしっかり踏ん張る\n   - 膝を軽く曲げて重心を下げる\n   - 上体をターンする方向に傾ける\n   - 膝が内側に入らないよう注意\n3. 新しい方向に3-4歩加速\n4. 左右両方向で実施\n\n【段階的進歩】\n• レベル1: 歩行ペースでのカット\n• レベル2: ジョギングペースでのカット\n• レベル3: 競技に近いスピードでのカット\n\n【チェックポイント】\n• 膝とつま先の向きが揃っている\n• バランスを保って着地している\n• スムーズな方向転換ができている',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 1,
      precautions: JSON.stringify(['十分なウォームアップ必須', '適切なカッティングフォーム', '膝の安定性確認', '段階的なスピードアップ']),
      contraindications: JSON.stringify(['医師の競技復帰許可がない場合', '膝の不安定性がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'スプリント（段階的）',
      description: '競技復帰に向けた段階的な走行練習',
      instructions: '【準備】\n• 20-30メートルの直線コースを確保\n• 適切なランニングシューズを着用\n• 十分なウォームアップを実施\n\n【段階1: 軽いジョギング（週1-2）】\n1. 60-70%程度の軽い強度で走行\n2. 距離：20メートル × 5本\n3. 各本の間は歩いて完全回復\n\n【段階2: 中強度走行（週3-4）】\n1. 80%程度の強度で走行\n2. 距離：30メートル × 4本\n3. 休息時間：各本の間90秒\n\n【段階3: 高強度スプリント（週5以降）】\n1. 90-95%の強度で走行\n2. 距離：30メートル × 3本\n3. 休息時間：各本の間2-3分\n\n【フォームチェック】\n• 膝の向きが正面を向いている\n• 着地時の膝の安定性\n• 左右対称な走行パターン\n• 痛みや違和感がない',
      difficulty_level: 'advanced',
      default_sets: 1,
      default_reps: 5,
      default_duration_seconds: 0,
      rest_time_seconds: 90,
      order_index: 2,
      precautions: JSON.stringify(['段階的な強度上昇', '痛みが出たら中止', '十分な休息', 'フォームの確認']),
      contraindications: JSON.stringify(['心肺機能に問題がある場合', '下肢に痛みがある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'ジャンプ&ランディング（上級）',
      description: '競技復帰に向けた高度なジャンプと着地の練習',
      instructions: '【準備】\n• 十分なスペースの確保\n• 適切なシューズの着用\n• ウォームアップの完了\n\n【エクササイズ1: リアクティブジャンプ】\n1. コーチや仲間の合図でジャンプ\n2. 様々な方向（前後左右）にジャンプ\n3. 予期しない方向への対応能力を向上\n4. 各セット：8-10回のジャンプ\n\n【エクササイズ2: デプスジャンプ】\n1. 30-40cmの台から飛び降り\n2. 着地と同時に垂直ジャンプ\n3. 着地時の衝撃吸収とリアクション力を向上\n4. 各セット：5-6回\n\n【エクササイズ3: マルチディレクション着地】\n1. 前方、後方、左右への連続ジャンプ\n2. 各方向での正確な着地を意識\n3. 方向転換時の膝の安定性を強化\n\n【着地時のチェックポイント】\n• 膝とつま先の向きが揃っている\n• 膝が内側に入らない（Knee-in回避）\n• 静音着地（着地音が小さい）\n• バランスの保持（3秒間静止）',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 6,
      default_duration_seconds: 3,
      rest_time_seconds: 120,
      order_index: 3,
      precautions: JSON.stringify(['十分な筋力獲得後に実施', '正確な着地フォーム', '疲労時は中止', '段階的な負荷増加']),
      contraindications: JSON.stringify(['膝の不安定性がある場合', '下肢筋力が不十分な場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('競技特異的訓練')?.id,
      name: 'スポーツ特異的動作練習',
      description: '各競技に特化した動作パターンの練習',
      instructions: '【サッカー・フットサル】\n• ボールを使ったドリブル練習\n• シュート動作（膝の安定性重視）\n• ヘディング時の着地練習\n\n【バスケットボール】\n• ドリブル中の急停止練習\n• ジャンプシュート動作\n• ディフェンス時の横移動\n\n【バレーボール】\n• スパイク時のジャンプと着地\n• レシーブ時の低い姿勢維持\n• ブロック時の着地動作\n\n【テニス・バドミントン】\n• 前後左右への素早い移動\n• ストップ＆ゴー動作\n• 回転動作（フォアハンド、バックハンド）\n\n【ランニング・陸上】\n• カーブ走行練習\n• ハードル動作（模擬）\n• スタートダッシュ練習\n\n【共通の注意点】\n• 競技復帰は医師の許可後\n• 段階的な負荷増加\n• 痛みや違和感があれば中止\n• 正しいフォームの維持\n• 十分な休息の確保',
      difficulty_level: 'advanced',
      default_sets: 3,
      default_reps: 8,
      default_duration_seconds: 0,
      rest_time_seconds: 120,
      order_index: 4,
      precautions: JSON.stringify(['医師の競技復帰許可必須', '段階的な練習強度', '正確なフォーム', '痛みモニタリング']),
      contraindications: JSON.stringify(['競技復帰許可がない場合', '基礎体力が不十分な場合']),
      requires_ai_analysis: true,
      is_active: true,
    },

    // 競技復帰期 - 外傷予防訓練
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'FIFA 11+プログラム',
      description: 'FIFA推奨の外傷予防プログラム（サッカー向け）',
      instructions: '【第1部: ランニング・エクササイズ（8分）】\n1. まっすぐ走る（2分）\n2. ヒップアウト走（膝を外に）\n3. ヒップイン走（膝を内に）\n4. サークル・パートナー走\n5. ジャンプ・ヘディング\n6. ショルダー・コンタクト走\n\n【第2部: 筋力・プライオ・バランス（10分）】\n1. ザ・ベンチ（体幹・太もも強化）\n2. サイドワイズ・ベンチ（体幹側面）\n3. ハムストリングス\n4. シングル・レッグ・スタンス\n5. スクワット\n6. ジャンピング\n\n【第3部: ランニング・エクササイズ（2分）】\n1. アクロス・ザ・ピッチ\n2. バウンディング\n3. プラント・アンド・カット\n\n【実施のポイント】\n• 週2-3回の頻度で実施\n• 練習前のウォームアップとして\n• 正確なフォームを重視\n• 段階的な強度増加',
      difficulty_level: 'advanced',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 1200, // 20分
      rest_time_seconds: 0,
      order_index: 1,
      precautions: JSON.stringify(['段階的な負荷増加', '正しいフォームの維持', '適切なウォームアップ']),
      contraindications: JSON.stringify(['急性期の症状がある場合', '下肢に痛みがある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'PEP（Prevent injury and Enhance Performance）',
      description: '女子アスリート向けACL損傷予防プログラム',
      instructions: '【ウォームアップ（5分）】\n• 軽いジョギング\n• サイドシャッフル\n• バックペダル\n• カリオカステップ\n\n【ストレッチング（3分）】\n• カーフストレッチ\n• クアドストレッチ\n• フィギュア4ストレッチ\n• ヒップフレクサーストレッチ\n\n【強化エクササイズ（15分）】\n1. ウォーキング・ランジ（各方向）\n2. ロシアン・ハムストリング\n3. シングル・トー・レイズ\n4. スクワット・ジャンプ\n5. バウンディング・イン・プレイス\n6. 180度ターン\n7. ブロッキング\n\n【クールダウン（2分）】\n• 軽いジョギング\n• 静的ストレッチ\n\n【実施頻度】\n• 週3回、練習前に実施\n• シーズンを通して継続\n• 各エクササイズは正確なフォームで実施',
      difficulty_level: 'advanced',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 1500, // 25分
      rest_time_seconds: 0,
      order_index: 2,
      precautions: JSON.stringify(['女性アスリートに特に推奨', '正確なフォーム', '継続的な実施']),
      contraindications: JSON.stringify(['急性損傷がある場合']),
      requires_ai_analysis: false,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'ニューロマスキュラートレーニング',
      description: '神経筋協調性を向上させる予防訓練',
      instructions: '【バランス・安定性訓練（10分）】\n1. 片足立ち（目を開けて/閉じて）\n2. 不安定面での片足立ち\n3. ダイナミック・バランス\n4. ボールキャッチ・バランス\n\n【プライオメトリック訓練（10分）】\n1. 両足ホッピング\n2. 片足ホッピング\n3. 前後ジャンプ\n4. 左右ジャンプ\n5. 対角ジャンプ\n\n【リアクション訓練（8分）】\n1. ミラー・エクササイズ\n2. 方向変換ドリル\n3. 急停止練習\n4. 予期しない方向への反応\n\n【機能的動作パターン（12分）】\n1. ファンクショナル・スクワット\n2. ランジ・パターン\n3. ステップ・アップ・ダウン\n4. カッティング・ムーブメント\n\n【効果】\n• 膝関節の安定性向上\n• 神経筋反応時間の短縮\n• 動的バランス能力の向上\n• 外傷リスクの軽減',
      difficulty_level: 'intermediate',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 2400, // 40分
      rest_time_seconds: 0,
      order_index: 3,
      precautions: JSON.stringify(['段階的な難易度上昇', '疲労時は中止', '正確な動作パターン']),
      contraindications: JSON.stringify(['急性症状がある場合', '平衡感覚に問題がある場合']),
      requires_ai_analysis: true,
      is_active: true,
    },
    {
      id: knex.raw('gen_random_uuid()'),
      category_id: getCategory('外傷予防訓練')?.id,
      name: 'セカンダリー・インジュリー予防',
      description: 'ACL再建術後の再受傷防止のための特別プログラム',
      instructions: '【日常チェック項目】\n• 朝の膝の状態確認\n• 痛みや腫れの有無\n• 可動域の確認\n• 筋力バランスの自己評価\n\n【練習前の必須チェック】\n1. 十分なウォームアップ（15分以上）\n2. 膝の安定性テスト\n3. 患側と健側の筋力差確認\n4. バランス能力の確認\n\n【練習中の注意点】\n• 疲労を感じたら無理をしない\n• 違和感があればすぐに中止\n• 水分補給の徹底\n• 適切な休息の確保\n\n【練習後のケア】\n1. クールダウン（10分以上）\n2. アイシング（必要に応じて）\n3. ストレッチング\n4. 膝の状態記録\n\n【長期管理】\n• 定期的な医師診察\n• フィジオセラピストとの連携\n• 筋力測定（3ヶ月毎）\n• MRI検査（医師判断）\n\n【再受傷の危険信号】\n• 膝の不安定感\n• 原因不明の痛み\n• 腫れの増大\n• 可動域の制限\n• パフォーマンスの低下',
      difficulty_level: 'beginner',
      default_sets: 1,
      default_reps: 1,
      default_duration_seconds: 0,
      rest_time_seconds: 0,
      order_index: 4,
      precautions: JSON.stringify(['継続的なモニタリング', '医療チームとの連携', '早期発見・早期対応']),
      contraindications: JSON.stringify(['無症状でも油断は禁物']),
      requires_ai_analysis: false,
      is_active: true,
    },
  ]);
};